build_packages.sh
it creates debian packages with the mimirsbrunn binaries.
the package has the git describe tag in it.
here is the first package content:
```
root@6efa0036e2af:/tmp/mimir# dpkg -c mimirsbrunn_0.0.1-1-gafc0bc3_amd64.deb 
drwx------ 0/0               0 2016-04-05 16:02 ./
drwxrwxr-x 0/0               0 2016-04-05 16:02 ./usr/
drwxrwxr-x 0/0               0 2016-04-05 16:02 ./usr/share/
drwxrwxr-x 0/0               0 2016-04-05 16:02 ./usr/share/doc/
drwxrwxr-x 0/0               0 2016-04-05 16:02 ./usr/share/doc/mimirsbrunn/
-rw-r--r-- 0/0             151 2016-04-05 16:02 ./usr/share/doc/mimirsbrunn/changelog.Debian.gz
drwxrwxr-x 0/0               0 2016-04-05 16:02 ./usr/bin/
-rwxrwxr-x 0/0         2089080 2016-04-05 15:32 ./usr/bin/bano2mimir
```
this uses fpm …
=> first draft of a debian creation script

Cargo.lock, Cargo.toml, build.rs, json/settings.json, src/bin/bano2mimir.rs, src/bin/osm2mimir.rs, src/lib.rs, src/lib.rs.in, src/rubber.rs
to abstract a bit some stuff, use an elastic search wrapper.
since the wrapper use elastic search 2 interfaces (and that we want to use it anyway), migrate settings to elastic search 2 version.
Note: this will break the build, you now at least need elactic search 2.0 (but the production version will be elastic search 2.3)
since rs-es use serde, use the '.in' trick to use it with rust stable (cf https://github.com/serde-rs/serde)
TODO:
* use the same input as osm2mimir (connection string or separate repositories ?)
* create the index with the wrapper (not done for the moment)
* use logger everywhere
* migrate osm2mimir to the wrapper
* attach the es type name to the objects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> use a elastic search wrapper

.gitignore, Cargo.lock, Cargo.toml, libs/docker_wrapper/src/lib.rs, libs/mimir/Cargo.toml, libs/mimir/src/lib.rs, libs/mimir/src/objects.rs.in, libs/mimir/src/rubber.rs, src/bin/bano2mimir.rs, src/bin/osm2mimir.rs, tests/bano2mimir_test.rs, tests/tests.rs
now an alias is created for each dataset/document type, and aliases are
used for the search to manage 0 downtime data update
egg, after an update the indexes will be:
```
❯ http ":9200/_aliases"
HTTP/1.1 200 OK
Content-Length: 77
Content-Type: application/json; charset=UTF-8
{
"munin_addr_fr_20160523_105906": {
"aliases": {
"munin": {}, 
"munin_addr_fr": {}
}
}
}
```
=> zero downtime data updates with indexes

libs/bragi/src/api.rs
when we'll want to do versioning on the API I think it will be better to
use the github versionning way.
by adding `ns.version("beta",
Versioning::AcceptHeader("autocomplete"));`
you can do:
`curl -H "Accept:application/vnd.autocomplete.beta+json"
":4000/autocomplete?q=12"`
=> remove the API versioning

Cargo.lock, Cargo.toml, libs/bragi/Cargo.toml, libs/docker_wrapper/Cargo.lock, libs/docker_wrapper/Cargo.toml, libs/docker_wrapper/src/lib.rs, libs/mimir/Cargo.toml, src/bin/bano2mimir.rs
bump mimir, bragi and docker_wrapper version
done a cargo update in the same time
and remove the curl dependency in the meantime
=> Bump sub crates version

libs/mimir/src/objects.rs.in, src/bin/osm2mimir.rs, tests/rubber_test.rs
according to the demand in this ticket: http://jira.canaltp.fr/browse/NAVP-592, we have to stock insee_id in admin
=> persist insee_id in admin

libs/bragi/src/model.rs.in
http://jira.canaltp.fr/browse/NAVP-592
add more admin details in street and address:
[x] tested with address  
[x] cannot test with street
```json
{
"Autocomplete": {
"type": "FeatureCollection",
"geocoding": {
"version": "0.1.0",
"query": ""
},
"features": [
{
"type": "Feature",
"geometry": {
"coordinates": [
2.3266459999999993,
48.803326
],
"type": "Point"
},
"properties": {
"geocoding": {
"id": "addr:2.326646;48.803326",
"type": "house",
"label": "22 Rue Guy de Gouyon du Verger, (Arcueil)",
"name": "22 Rue Guy de Gouyon du Verger, (Arcueil)",
"housenumber": "22",
"street": "Rue Guy de Gouyon du Verger, (Arcueil)",
"postcode": "94110",
"city": "Arcueil",
"administrative_regions": [
{
"id": "admin:fr:94003",
"insee": "94003",
"level": 8,
"name": "Arcueil",
"zip_code": "94110",
"weight": …
```
=> Add administrative regions in bragi

libs/bragi/src/model.in.rs
Before:
- label: "Mairie de Campile (Campile)",
- name: "Mairie de Campile (Campile)"
After:
- label: "Mairie de Campile (Campile)",
- name: "Mairie de Campile"
=> [Bragi] fixed POI name

libs/bragi/src/model.in.rs, tests/bragi_test.rs
in the 'city' field there should be only the city name, not the label
Note: the field is not used in navitia, it's only for geocodejson
compatibility
=> for geocoding admin

libs/bragi/src/query.rs, tests/bragi_test.rs
when we search [0, 2] fields, we need to match 100% of them
when we search [0, 4] fields, we need to match 90% of them
when we [5, +] fields, we only need to match 70% on them 
this way if the has more fields than the documents (additional information like country, the region, ...) they can be ignored
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-minimum-should-match.html
we this on go from 938 fails on geocoding tester (on idf) to 881
Note: the impact on performance seems negligeable
=> relax the minimum match filter

libs/bragi/src/query.rs, tests/bragi_filter_types_test.rs
When we search stop areas with no dataset we should return nothing
=> Fixed result when no ES indexes

.travis.yml, libs/mimir/src/rubber.rs, tests/bano2mimir_test.rs, tests/rubber_test.rs, tests/tests.rs
sometimes when a process fail some 'ghost' indexes remain, we now clean
them up
=> cleanup old useless indexes

src/bin/stops2mimir.rs, tests/bragi_stops_test.rs, tests/fixtures/stops.txt, tests/stops2mimir_test.rs
This modification calculates weight of each StopArea which is the number of it's StopPoint.
=> mimir: Calculate stop_area weight by stop_point count

json/settings.json, libs/bragi/src/query.rs
That's a bit worst on geocoder-tester (361 -> 394), but remove strange artefacts around zip prefix and house number
=> Search on word and not prefix on zip code

libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/bin/stops2mimir.rs, tests/bragi_stops_test.rs, tests/fixtures/stops.txt, tests/fixtures/stops_dataset2.txt, tests/stops2mimir_test.rs, tests/tests.rs
As a step to have an auto-completion working cross navitia's coverages, when we import a stop we aggregate all the stops in a unique index.
For the moment the stops are 'merged' only if they got the same ID (that will likely change) and we retain the data only from one of the merged stop.
An additional stop field has been added, `coverages` with the list of the stop's coverage.
This will make it possible for bragi to filter a query on a set of coverage.
There is not the bragi part in this PR
=> Add a global stops index

json/settings.json, libs/bragi/src/query.rs
This should greatly improve the speed of bragi, chosen values are still a bit experimental, with these one there is 8 more failure on geocoder-tester but overall test are down to 104sec while they were taking 180 seconds before.
TODO:
```
before: ============= 380 failed, 1712 passed, 1 skipped in 185.53 seconds =============
after: ============= 368 failed, 1724 passed, 1 skipped in 94.98 seconds ==============
```
poke @antoine-de  
This PR adds a new index, so bragi will require that all data have been re-indexed before working correctly. The previous version of bragi will still works even with the new indexes.
=> set different MinimumShouldMatch per size of the query

libs/mimir/src/rubber.rs, tests/rubber_test.rs, tests/tests.rs
when bulk inserting empty iterator (or if the number of elements to insert modulo `chunk_size` was 0 ), rubber was crashing
=> fix bulk bug

src/bin/openaddresses2mimir.rs, tests/fixtures/sample-oa.csv, tests/openaddresses2mimir_test.rs, tests/tests.rs
connector to import data from https://openaddresses.io/, so now you can have addresses from all around the world :world_map: 
you can use this to import french data too if you want, but beware that it's the [ban](https://adresse.data.gouv.fr/), not [bano](http://openstreetmap.fr/bano).
(and it's a bit cumbersome since openaddresse split the files by regions)
=> Import OpenAddresses

libs/bragi/src/api.rs, libs/bragi/src/model.rs, libs/mimir/src/objects.rs, libs/osm_builder/src/lib.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/stops2mimir.rs, src/boundaries.rs, src/osm_reader/admin.rs, src/osm_reader/osm_utils.rs, src/osm_reader/poi.rs, src/osm_reader/street.rs, tests/rubber_test.rs, tests/tests.rs
we handle coordinate as `x`/`y` internally, but it the end we want `lon`/`lat` and there was a classical swap between `lon` and `lat`.
The swap was not detected before because bragi swap again the coordinates so in bragi the coordinates are ok even if they are inversed in ES 🤣 
to clarify, now we always do `lon`=`x` and `lat`=`y`, and we always give first `lon` then `lat` in the coordinate constructor
WARNING, this is a breaking change, I don't see any (easy) way to make this retrocompatible, It will need a full reindex !
=> Fix lat lon in ES

libs/mimir/src/rubber.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, src/stops.rs, tests/rubber_test.rs
a common pattern while using Rubber is (the example is taken from `bano2mimir`):
```rust
let addr_index = rubber.make_index(Addr::doc_type(), dataset)?;
rubber.bulk_index(&addr_index, iter)?;
rubber.publish_index(Addr::doc_type(), dataset, addr_index, Addr::is_geo_data())?
```
it feels error prone to write it like this.
This PR add a `TypedIndex<T: MimirObject>` for more compil time check
The same code is now written
```rust
let addr_index = rubber.make_index(dataset)?; // <- since we bulk insert addresses, the compiler knows it's a TypedIndex<Addr>
rubber.bulk_index(&addr_index, iter)?;
rubber.publish_index(dataset, addr_index)?
```
with explicit types it is
```rust
let addr_index = rubber.make_index::<Addr>(dataset)?;
rubber.bulk_index::<Addr>(&addr_index, iter)?; …
```
=> stricter types in Rubber

libs/bragi/src/api.rs, libs/bragi/src/model.rs, tests/bragi_osm_test.rs
now that the cities are correctly tagged, we can associate the object
(field `city`/`citycode`) to a street and not to the first admins
in our dataset the `city` field of the `rue saint antoine` was associated to `Quartier de l'Arsenal`
=> fix city association

Cargo.lock, libs/bragi/Cargo.toml, libs/bragi/src/api.rs, libs/bragi/src/lib.rs, libs/bragi/src/model.rs, libs/bragi/src/query.rs, libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/admin_geofinder.rs, src/bin/stops2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/street.rs, src/stops.rs, tests/bragi_filter_types_test.rs, tests/bragi_poi_test.rs, tests/bragi_stops_test.rs, tests/canonical_import_process_test.rs, tests/tests.rs
before the could get `200` response with an error message.
Use `Failure` in bragi to get better error.
we now have:
for `/autocomplete`:
no es => ServiceUnavailable (503)
other error => InternalError (500)
`/features`
no object => NotFound 404
no index (invalid `pt_dataset` parameter) => NotFound 404 (different
message)
no es => ServiceUnavailable (503)
other error => InternalError (500)
`/status` => always 200 if bragi is up
Warming this is a breaking change !
but I think it's cleaner and I don't know of integration that this might
break. the only other solution I see is to do another api version but
that seems a bit overkill
related to https://github.com/CanalTP/mimirsbrunn/issues/179
=> better api status code

libs/bragi/src/query.rs, libs/mimir/src/rubber.rs, src/bin/osm2mimir.rs, src/osm_reader/admin.rs
now the weight is only the population of an admin, not the number of street in it.
This will clean the model by removing the uggly need for the `weight` to be a Cell (or the even complex `Weight` of the PR #224 
the results seems affected, but only a bit (at lest in france where the `population` tag is well filled)
geocoder results (run by [this script](https://github.com/antoine-de/geocoder-tester/blob/af68e546e1a05bf5feb29f62cb77c3b5ed681dd9/run_qwant.sh)):
`results_master_ctp` is the current master filled with osm for admin, streets and poi, and bano for addresses
`results_master_ctp_pop_weight_clean` is this PR with the same data
```diff
--- a/results_master_ctp/run.log
+++ b/results_master_ctp_pop_weight_clean/run.log
@@ -1,13 +1,13 @@
-testing master_ctp on …
```
=> change the weight mechanism

json/addr_settings.json, json/admin_settings.json, json/poi_settings.json, json/stop_settings.json, json/street_settings.json, libs/bragi/src/model.rs, libs/bragi/src/query.rs, libs/mimir/src/objects.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, src/osm_reader/street.rs, tests/rubber_test.rs
Since #211 as it is worsen the geocoder-test, this PR includes #211 and #213 and add some more stuff:
* add a `name` (correctly indexed) the the addresses (so they can also enjoy theboost on the `name`
* do not take the label's size into account (as the label is a generated field). check [the commit](https://github.com/CanalTP/mimirsbrunn/commit/1075633de9f2504bcaf45f10db67f98fdaec62bb) for more information
The geocoder tester (run with [this script](https://github.com/QwantResearch/geocoder-tester/blob/master/run_qwant.sh)) seems happy with this version:
```diff
--- results on master 
+++ results on this PR
-summary for france_autre ==== 1630 failed, 9386 passed, 1 skipped, 1066 deselected in 823.38 seconds ====
-++++++++++ result france_autre: 85% (/) (/11016)
+summary for france_autre …
```
=> Better search

ci/gitlab/.gitlab-ci.yml, ci/gitlab/docker-compose.build.yml, ci/gitlab/download_data.sh, ci/gitlab/import_settings_with_cosmogony.yml, ci/gitlab/import_settings_without_cosmogony.yml, ci/gitlab/init.sh
Following #233, here are configuration files to trigger geocoding tests in a gitlab-ci pipeline.
Using [docker_mimir](https://github.com/QwantResearch/docker_mimir), a docker composition will build images, import datasets into mimirsbrunn, run geocoder-tester and create artifacts with detailed results.
**Requirements:**
* GitLab CI must be enabled on a mirror of this repository, and configured to use 
`ci/gitlab/.gitlab-ci.yml` as the config path.
* Register a runner with "docker-privileged" mode (necessary to use "docker inside docker": build docker images on the current branch, and run docker-compose). 
See https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-executor
(This page also describes other approaches that could be used to make the runner execute …
=> Add GitLab-CI pipeline configuration to run geocoder tester

libs/bragi/src/query.rs, libs/mimir/src/rubber.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, tests/bano2mimir_test.rs, tests/fixtures/sample-bano.csv, tests/fixtures/sample-oa.csv, tests/openaddresses2mimir_test.rs
Some addresses have a void street.name field.
They shouldn't be imported since they decrease the reverse geocoding quality and furthermore are not 'searchable' in the autocomplete.
This PR filters these addresses + adds the corresponding tests.
PS: commit 4998fcd32ddfd95269d25f1eb06f6658bc3b5bc0 fails the `cargo fmt --all -- --check` so I format it the correct way
=> Address must have street name

json/addr_settings.json, json/admin_settings.json, json/poi_settings.json, json/stop_settings.json, json/street_settings.json, libs/bragi/src/lib.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/mimir_init.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/stops2mimir.rs, tests/osm2mimir_test.rs
by default elasticsearch index all unknown field (not in the mapping).
this means that it will take some time and some space to index some useless field. Like for example the big admins name (thrice in the poi index :wink: )
https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html
adding `"dynamic": "false"` to the mapping tells ES not to index the unknown field (but they are still stored).
Note: do not merge this PR yet, I opened it for review, and I'm waiting for the data import process to give figures about the impact on the index time/space
=> Do not index useless fields

.travis.yml, libs/bragi/src/api.rs, libs/bragi/src/query.rs, libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/stops2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/poi.rs, src/osm_reader/street.rs, src/stops.rs, tests/bragi_poi_test.rs, tests/bragi_stops_test.rs, tests/tests.rs
A recent PR https://github.com/CanalTP/mimirsbrunn/pull/226 added a too verbose log in case of an ignored address.
This PR just remove the useless part of this log.
The change in the log has no impact on the existing tests, so no test comes along this small fix.
=> Remove a verbose useless log

src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs
in the bano dataset there are 284917 addresses without a street name so
it flood the logs, I propose to move the log as debug (are remove the
debug dump of the address
=> remove useless log

Cargo.lock, libs/bragi/Cargo.toml, libs/bragi/src/api.rs, libs/bragi/src/lib.rs, libs/bragi/src/model.rs, libs/bragi/src/query.rs, libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/mimir_init.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/stops2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/street.rs, src/stops.rs, tests/bragi_poi_test.rs, tests/bragi_stops_test.rs, tests/tests.rs
Add distance between input coords and feature objects in json response, when we have request with {lat,lon} params like :
```
/autocomplete?q=14 juillet&_all_data=true&lat=48.526578&lon=2.679347
```
The corresponding response is :
```
...
],
"feed_publishers": [
{
"id": "",
"license": "",
"name": "",
"url": ""
}
]
}
},
"distance": 100                 <----------------------- in meters
},
{
"type": "Feature",
"geometry": {
"coordinates": [
2.56849,
48.914572
...
```
=> Bragi: Add distance for features

libs/mimir/src/objects.rs, src/admin_geofinder.rs, src/bin/cosmogony2mimir.rs, src/osm_reader/admin.rs, tests/rubber_test.rs
Our data import process to import the addresses is very long, even on a quite small dataset like France.
The major time (80% of the run time in our case) is taken to associate an admin to an address.
To do this, mimir load all the admin in a rtree and check the admin boundaries.
Since we use [cosmogony](https://github.com/osm-without-borders/cosmogony) to import our admins, we got lots of them (compared to the basic CanalTP use case that read only the admin 8 from osm).
This PR speed up the admin association by using the cosmogony hierarchy.
Cosmogony already do lots of geographic inclusion to produce a hierachy. The idea is to store this hierarchy in ES (only storing the parent's ID will not overload the db) and skip some `contains` based on this hierarchy.
We also consider that we …
=> Admin lookup speedup

libs/bragi/src/model.rs, libs/mimir/src/objects.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/street.rs, src/utils.rs, tests/cosmogony2mimir_test.rs, tests/osm2mimir_test.rs, tests/rubber_test.rs
now that there has been a mimir release, we can drop the retro compatibility on the old stuff and get rid of the warnings:
* remove `AdminType` (deprecated in favor on the more fine grained ZoneType)
* remove `street_name` (renamed `name` for coherence and better ES boost on the `name` field search
* remove a `failure` warning
There is on last warning in the project that will be corrected in another PR (since there can be more discussion on it, I prefer to split it).
=> Clean warning

libs/bragi/src/query.rs, tests/bragi_filter_types_test.rs
A test method was never called (my bad :confused: ).
The thing is that the test was not passing either, because if we look for a non-existing index, we won't have a specific error as the test state, but a generic one (no object found). (I think this was implemented like this because an index might be missing if no data of that type has been imported yet).
This is done this way because the rubber `get_indexes` method always returns a non-empty list of elements (there is always at least "munin_geo_data" returned)
I think the get_indexes must also be refactored, but it will be for another PR.
I'd vote for:
* https://github.com/CanalTP/mimirsbrunn/blob/master/libs/mimir/src/rubber.rs#L233 => I don't see why it should be the case, we should add all pt_dataset
* if a pt_dataset does not exist, …
=> fix useless method

Cargo.lock, libs/bragi/src/query.rs, libs/mimir/src/rubber.rs
We use `ignore_unavailable` to ignore index that don't exist to not have
to check if the index exist before.
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/multi-index.html
waiting for https://github.com/benashford/rs-es/pull/121 fork in the second commit of this PR, don't read that.
=> Don't check if index exist before doing a query

libs/bragi/src/model.rs, libs/mimir/src/objects.rs, src/admin_geofinder.rs, src/bin/cosmogony2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/osm_utils.rs, tests/canonical_import_process_test.rs, tests/cosmogony2mimir_test.rs, tests/rubber_test.rs
add codes to Admins (like it is done for stops)
We need this mainly to associate a poi to a country (to correctly format
the phone number)
Since a poi is associated to it's admin hierarchy we only need to return
the country codes from the osm tags.
To be a bit more generic than our need, we fill the `codes` with:
* ISO3166 codes
* ref:* tags (to get NUTS codes, INSEE code (even if we have a custom
field for them), ...)
=> add codes to admin

json/addr_settings.json, json/admin_settings.json, json/poi_settings.json, json/settings.json, json/stop_settings.json, json/street_settings.json, libs/mimir/src/rubber.rs, src/addr_reader.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/stops2mimir.rs, src/stops.rs, tests/cosmogony2mimir_test.rs, tests/rubber_test.rs
fix https://github.com/CanalTP/mimirsbrunn/issues/267
add 2 cli parameters on each data importer:
* `--nb-shards`
* `--nb-replicas`
for `osm2mimir` it is a bit more complex since it can import several
types, so we can add several cli param, one for each type:
`--nb-poi-shards` `--nb-admin-shards` `--nb-street-shards` and the same
for the replicas.
=> add cli params to control the number of shard/replicas

json/addr_settings.json, json/admin_settings.json, json/poi_settings.json, json/stop_settings.json, json/street_settings.json
We don't want to use the size of a label since it is generated.
It has been implemented in https://github.com/CanalTP/mimirsbrunn/pull/229 but I forgot to also remove the norms for the full field (we want to boost a response when we match entire tokens.
The test case for us was that the query `Lyon` was having the results:
```
* Lyon, Coahoma County, Mississippi, United States <---- small village in
mississipi
* Lyon, Métropole de Lyon, Auvergne-Rhône-Alpes, France <---- big french
city with a lot of population
```
with this PR, we now have the french city first
=> Fix labels normalization

Cargo.lock, Cargo.toml, libs/bragi/Cargo.toml, libs/bragi/src/api.rs, libs/bragi/src/lib.rs, libs/bragi/src/query.rs, libs/mimir/Cargo.toml, libs/mimir/src/lib.rs, libs/mimir/src/rubber.rs, src/osm_reader/poi.rs, tests/tests.rs
A timeout parameter has been recently added (https://github.com/CanalTP/mimirsbrunn/commit/4b2d149bcc2958736791ab1073fed7f0e25b5f7b) but it handles only the network and not the time limit allowed to the ES query.
This PR proposes to use the same timeout both for the network and for the query.
This parameter can be defined at two places:
- as a command line argument launching bragi: `default_es_max_timeout=...`
- or directly into the user query: `timeout=...`
In this PR we changed the previous behavior: instead to overwrite the default timeout with the query one, we keep the minimum. In other words the default timeout becomes the max.
=> Timeout for the ES query

libs/bragi/src/model.rs, tests/canonical_import_process_test.rs
return in the json response a generic "internal server error" on
error 500 (or "service unavailable" when ES is not reachable, status code 503) not to have
error messages like:
```json
{
"short":"query error",
"long":"invalid query 503 Service Unavailable -
{\"error\":{\"root_cause\":[],\"type\":\"search_phase_execution_exception\",\"reason\":\"all
shards
failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[]},\"status\":503}"
}
```
the error is logged to trace it.
=> Do not expose internal serveur message to the client

libs/bragi/src/api.rs, libs/bragi/src/lib.rs, libs/bragi/src/query.rs, libs/docker_wrapper/src/lib.rs, libs/mimir/src/lib.rs, libs/mimir/src/rubber.rs, src/addr_reader.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/ntfs2mimir.rs, src/bin/osm2mimir.rs, src/bin/stops2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/osm_utils.rs, src/osm_reader/poi.rs, src/osm_reader/street.rs, tests/bano2mimir_test.rs, tests/bragi_filter_types_test.rs, tests/bragi_osm_test.rs, tests/bragi_stops_test.rs, tests/bragi_synonyms_test.rs, tests/bragi_three_cities_test.rs, tests/canonical_import_process_test.rs, tests/cosmogony2mimir_test.rs, tests/openaddresses2mimir_test.rs, tests/osm2mimir_test.rs, tests/rubber_test.rs, tests/stops2mimir_test.rs, tests/tests.rs
We want streets id as stable as possible.
The solution this PR proposes is the following:
- for streets divided by several ways we take the id of the corresponding relation (tagged "type=associatedStreet") with the prefix "street:osm:rel:<id>"
- for all other streets we select the min id of the corresponding ways with the prefix "street:osm:way:<id>"
=> More stable street id

libs/mimir/src/rubber.rs, tests/bano2mimir_test.rs, tests/bragi_bano_test.rs, tests/fixtures/sample-bano.csv
As a Qwant Maps user pointed out (https://github.com/QwantResearch/qwantmaps/issues/28), the `/reverse` endpoint may return a wrong address is some cases. This is due to the gaussian decay function that returns **the exact same score** for multiple addresses that are only a few meters apart.
This PR suggests to replace the current function with an [exponential decay function](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/decay-functions.html#img-decay-functions).
Note that this change is only about the `build_proximity_with_boost` function that is defined in `rubber.rs` and used by the reverse geocoder.  
A [similar function exists](https://github.com/CanalTP/mimirsbrunn/blob/master/libs/bragi/src/query.rs#L103) in the autocomplete query and keeps unchanged.
=> reverse: Fix proximity score to always return the closest address

libs/bragi/src/query.rs
* Define an arbitrary boost on  `names.*` and `labels.*` fields.  
(Improve rankings of admins with translated names, compared to other objects with matching name)
**Without boost** (planet)
```
region                 | category | failed | total | ratio |    duration    
---------------------------------------|----------|--------|-------|-------|----------------
test_admin_capital_cities_i18n_en.csv |  admins  |  320   |  486  |  34%  | 0:00:06.720000 
test_admin_cities.csv         |  admins  |  491   |  940  |  48%  | 0:00:12.700000 
test_admin_cities_i18n_en.csv     |  admins  |  513   |  940  |  45%  | 0:00:12.700000 
test_admin_cities_i18n_fr.csv     |  admins  |  527   |  940  |  44%  | 0:00:08.740000 
_                   |  fuzzy   |  342   |  993  |  66%  | 0:00:35.130000 
_ …
```
=> Improvements in i18n query

libs/bragi/src/routes/autocomplete.rs, libs/bragi/src/routes/features.rs, libs/bragi/src/routes/params.rs, libs/bragi/src/routes/reverse.rs, tests/canonical_import_process_test.rs
the timeout handling has been broken by
https://github.com/CanalTP/mimirsbrunn/pull/286
this fixes it by parsing the timeout as an integer as before (and not a
duration)
Note: without this, the navitia integration is broken and maybe others too. poke @amatissart
=> correct timeout handling

src/bin/cosmogony2mimir.rs, src/utils.rs
We read the file two times now, it doesn't seem to have any impacts on performance:
Before:
duration: 4.25 min
memory: 10 go
After:
duration: 4.17 min
memory: 250 mo
I'am not a fan of the `ZoneWeight` struct, I would like to create the map and the max_weight in one shot, but without having that struct, and I don't know how to do that without reading one more time :D
=> Use streaming capabilities of cosmogony to reduce memory usage

json/poi_settings.json, libs/bragi/src/model.rs, libs/mimir/src/objects.rs, src/osm_reader/poi.rs, src/utils.rs, tests/bragi_poi_test.rs, tests/tests.rs
This PR is the extension of https://github.com/CanalTP/mimirsbrunn/pull/285 for POI.
Basically it simply adds the 'names' and 'labels' fields to the POI object.
The index POI settings are changed accordingly to these changes.
A basic test comes along the PR.
=> add labels/names fields

src/osm_reader/admin.rs
For coherence, when reading admins from osm, the id of those admins is now `admin:osm:relation:{osm_id}` (like cosmogony's id)
=> Change the osm admin's id

src/admin_geofinder.rs, src/bin/cosmogony2mimir.rs
Some city_district have the same insee than their city: we were loosing
some admins during the import and had an infinite loop when recreating the
hierarchy of addresses.
Now we only construct admin's id with insee for cities, and we always
create the id with `zones_osm_id` to make sure we have coherent id between
admin and their parents
This PR also include a check when constructing the admin hierarchies to prevent infinite loop: if we add an admin that had already been added we stop the loop.
=> Only use french retrocompatible id for cities

Cargo.lock, Cargo.toml, libs/bragi/Cargo.toml, libs/bragi/src/query.rs, libs/bragi/src/routes/reverse.rs, libs/docker_wrapper/Cargo.toml, libs/docker_wrapper/src/lib.rs, libs/mimir/Cargo.toml, libs/mimir/src/rubber.rs, src/bin/ntfs2mimir.rs, tests/bano2mimir_test.rs, tests/openaddresses2mimir_test.rs, tests/osm2mimir_bano2mimir_test.rs, tests/rubber_test.rs, tests/tests.rs
rs-es has been update to use [reqwest](https://docs.rs/reqwest/0.9.14/reqwest/)
in place of hyper directly. This update allows us to move from the very old hyper that was used :tada:
Reqwest look a lot like hyper 0.10, so there is only a few changes that are mostly cosmetics.
navitia_model has been renamed in `transit_model` and is not published on crates.io.
=> update rs-es and navitia_model

libs/bragi/src/model.rs, tests/bragi_bano_test.rs
following #304 output country_codes in the api
we do not implement the search on this field via bragi for the moment, but it would be easy to do so if the need arise
=> output country_codes

libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/stops.rs
fetching the admins only from the current dataset was not agodd idea, we need to fetch the admins from all the datasets.
this way we'll be able to import osm data either on a france dataset and on a nl dataset, and use the admins from cosmogony
it would be better to lazily fetch the admins, but it would be more difficult to implement, so I went to the easiest solution (and it's quite the same as before for either Qwant setup and Kisio's)
=> Always fetch all admins

Cargo.lock, Cargo.toml, libs/bragi/Cargo.toml, libs/bragi/src/lib.rs, libs/bragi/src/query.rs, libs/bragi/src/routes/autocomplete.rs, libs/bragi/src/routes/features.rs, libs/bragi/src/routes/params.rs, libs/bragi/src/routes/reverse.rs, libs/bragi/src/routes/status.rs, libs/mimir/Cargo.toml, libs/mimir/src/rubber.rs, src/osm_reader/poi.rs, tests/bragi_bano_test.rs, tests/bragi_filter_types_test.rs, tests/bragi_ntfs_test.rs, tests/bragi_osm_test.rs, tests/bragi_poi_test.rs, tests/bragi_stops_test.rs, tests/bragi_synonyms_test.rs, tests/bragi_three_cities_test.rs, tests/canonical_import_process_test.rs, tests/tests.rs
Reuse the same connections when querying ES by storing a rubber in the Actix's `State`
since synchronous reqwest 0.9.18 does not work in a asynchronous (actix) context, we are not able to update reqwest to be able to change the timeout.
To work around this limitation, we create 1 rubber / route (/autocomplete, /features and /reverse), and use this rubber (and thus the connection pool associated) if a different timeout has not been specified in the query.
That is not very neat, but this greatly reduce the cost calling ES (from 20ms to 1ms on my computer for dumb query)
depends on https://github.com/benashford/rs-es/pull/137
=> Use a connection pool

libs/mimir/src/rubber.rs, libs/tools/src/lib.rs, src/addr_reader.rs, src/bin/cosmogony2mimir.rs, src/bin/osm2mimir.rs, src/bin/poi2mimir.rs, src/stops.rs, tests/bragi_poi_test.rs, tests/poi2mimir_test.rs, tests/rubber_test.rs
This commit adds a flag 'private' to rubber's `publish_index` function
so that a private index is not aliased by global indices, eg munin.
This flag is propagated to poi2mimir's command line, so that we can
import private POIs.
There are also modifications of the elastic search wrapper to allow
queries on non global indices.
=> Feature: Handling private indices

.travis.yml, docker/Dockerfile_bragi, docker/Dockerfile_import
the update of the crate prometheus forces us to update the rust minimum
supported version
also remove the travis building on beta/nighlty
=> update the minimum supported rust version

libs/docker_wrapper/src/lib.rs, libs/mimir/src/rubber.rs, libs/tools/src/lib.rs
A test which targets an invalid elastic search URL may or may not fail:
The test expects a 503 response from Bragi, but if Bragi's timeout is
shorter than the DNS, then a get() would return a future timeout, which
fails the test.
This change introduces:
1. A large (10 secs) timeout on docker_wrapper's rubber
2. A slight modification of the Rubber::new_with_timeout function,
which now takes an Into<Option<Duration>> instead of just an
Option<Duration>
=> Fix timeout issue in test

libs/bragi/src/extractors.rs, libs/bragi/src/lib.rs, libs/bragi/src/model.rs, libs/bragi/src/prometheus_middleware.rs, libs/bragi/src/query.rs, libs/mimir/src/lib.rs, libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/addr_reader.rs, src/labels.rs, src/lib.rs, src/osm_reader/admin.rs, src/osm_reader/poi.rs, src/osm_reader/street.rs, src/stops.rs, src/utils.rs
I need a tool that targets bragi's web API.
This tool needs to be aware of the parameters used by bragi.
These parameters were not publicly exposed.
There is also a function to generate query parameters, so that they can be easily incorporated in, eg reqwest:
```
let bragi_params = Params { ... };
let query_params = autocomplete_params_to_query_params(bragi_params);
Client::new().post(...).query(query_params).send()...
```
An alternative to the function might be to use Into<Vec<String, String>> ?
An alternative would be to use OpenAPI, to open the bragi API to other languages...
=> extern crate -> rust 2018

libs/bragi/src/query.rs, tests/bragi_three_cities_test.rs, tests/fixtures/stops_shape.txt
This change introduces a modification of the filtering based on shapes:
The filter becomes inactive for stop areas.
=> Modify the filter on shape

Cargo.lock, libs/bragi/Cargo.toml, libs/bragi/src/model.rs, libs/bragi/src/query.rs, libs/bragi/src/routes/autocomplete.rs, libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/poi2mimir.rs, src/osm_reader/admin.rs, src/osm_reader/poi.rs, src/osm_reader/street.rs
This change adds a query url parameter to bragi (`debug=true`),
which triggers a so called explain query in elasticsearch, and
forwards the results back as json.
By default, when the parameter is not present, the flag debug is false.
This new feature can be used to analyze the score assigned by
elasticsearch to a result.
This change adds an 'explain' object to a geocodejson feature object,
which is not part of the initial specification.
This change addresses issue #214
=> Feature: Add explain to bragi

libs/bragi/src/lib.rs, libs/bragi/src/model.rs, libs/bragi/src/query.rs, libs/docker_wrapper/src/lib.rs, libs/tools/src/lib.rs, src/addr_reader.rs, src/bin/bano2mimir.rs, src/bin/bragi.rs, src/bin/cosmogony2mimir.rs, src/bin/mimir_init.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/poi2mimir.rs, src/bin/stops2mimir.rs, src/labels.rs, src/osm_reader/admin.rs, src/osm_reader/poi.rs, src/osm_reader/street.rs, src/stops.rs, src/utils.rs
This change removes a lot of compilation warnings I have, and that were due to rust 2018 compliance
=> Remove #[macro_use] warning

libs/bragi/src/lib.rs, libs/bragi/src/routes/autocomplete.rs, libs/bragi/src/routes/features.rs, libs/bragi/src/routes/reverse.rs
This PR make bragi output a cache header for every requests on
/features, /autocomplete, /reverse.
By default cache is enabled and set to 1H.
This header will be used by http clients to cache results, it will also
be used by caching proxy like varnish.
=> Add cache header to bragi http response

Cargo.lock, Cargo.toml, docker/Dockerfile_import, src/bin/osm2mimir.rs, src/osm_reader/osm_utils.rs, src/osm_reader/street.rs, tests/osm2mimir_test.rs, tests/tests.rs
Depends on https://github.com/TeXitoi/osmpbfreader-rs/pull/22
When running on central america with osm2mimir, the memory consumption goes from 5464 MB to 4790 MB. Considering this is a **very** small file, I expect the difference to be way bigger for the whole world. Only question: should I provide an option for this or not?
=> Greatly improve memory usage in osm2mimir streets computation

src/addr_reader.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs
bano2mimir sometimes resulted in panics when the id was less than 10
character long. This change logs (warning) those cases, and skips to the
next CSV line.
=> Modify import_address to use Result<Addr, Err>

src/bin/poi2mimir.rs, tests/poi2mimir_test.rs
Currently we get the admins for a poi by querying Elasticsearch
via rubber to get the closest address, and then get the admins from
that address.
Here, we build an in-memory AdminGeoFinder from all the admins in
Elasticsearch, and then query the geofinder to get the admins directly.
I have tested by inserting all the data in Ile de France (OSM, Bano, NTFS),
and then adding one poi. When we query Bragi with type[]='poi', we get the
same admins for that poi, before and after the patch.
=> Use the AdminGeoFinder with poi2mimir

Cargo.lock, Cargo.toml
This change from navitia_poi_model fixes an error that occured when
importing poi files. The absence of 'poi_properties.txt' would be
flagged as an error, but in fact it just means that there is no
additional properties.
I have tested this change by creating a poi file without poi_properties.txt, and importing it
with poi2mimir.
=> Bump navitia_poi_model

src/osm_reader/street.rs, tests/osm2mimir_test.rs
'bus_platform', for example, should not be indexed.
=> OSM2Mimir: Exclude certain kind of highway

.travis.yml, docker/Dockerfile_bragi, docker/Dockerfile_import
With the upcoming changes, the minimum version of the rust toolchain that compiles the project has changed from 1.36 -> 1.39.
=> Mininale Supported Rust Toolchain version 1.39.0

Cargo.lock, Cargo.toml, src/addr_reader.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs
Add a `gzip` parameter for BANO and OpenAddresses importers, this allows to import gziped CSV files. For example:
```bash
cargo run --release --bin openaddresses2mimir -- --gzip --input=luxembourg.csv.gz --connection-string=$ES_ADDRESS
```
Our use-case is that we intend to import a big amount of addresses that were obtained by merging several sources and that we output using OpenAddresses format.
In general it may still be a nice feature, at least for BANO importer as compressed CSV files are distributed.
=> add a gzip option for CSV addresses importers

Cargo.lock, Cargo.toml, libs/bragi/Cargo.toml, libs/mimir/Cargo.toml, libs/mimir/src/objects.rs, libs/mimir/src/rubber.rs, src/addr_reader.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs
gst is unmaintained (4 years) and needs to be replaced.
rstar is the obvious contender for replacing gst.
By making use of geo algorithm, this change simplifies the code
for the AdminGeoFinder.
This proposed change has a breaking consequence however. We can no
longer insert admins with boundaries from 'osm2mimir'. We can still
do with 'cosmogony and cosmogony2mimir'. Here is why:
In the AdminGeoFinder, we strip the boundary from the Admin, to save
memory. In 'osm2mimir', we store the admins found in the pbf file in
the AdminGeoFinder, and then iterate over them to index them in
Elasticsearch. With cosmogony2mimir, we simply iterate over all the
admins found in the cosmogony file, and index them (we don't use the
AdminGeoFinder).
=> WIP Replace gst with rstar; Update dependencies.

src/bin/openaddresses2mimir.rs
This is just a dumb mistake introduced in https://github.com/CanalTP/mimirsbrunn/pull/375.
I think it was introduced because I have been careless when applying changes for https://github.com/CanalTP/mimirsbrunn/pull/375#discussion_r380779014 (which also applied to this section of code).
=> fix openaddresses2mimir skipping non-compressed files

libs/bragi/src/prometheus_middleware.rs
Two small fixes about prometheus metrics:
* Do not use an arbitrary path as the "handler" label.
Prometheus recommends not to use metric labels to store an unbounded number of values. In the current implementation, any 404 request with an incorrect path would create a new time series in the prometheus response, that could lead to memory exhaustion in the monitoring stack.  
See https://prometheus.io/docs/practices/naming/#labels for more details  
This PR suggests to use an empty string as a fallback value for unknown paths.
* Set a correct `Content-Type` header value on the /metrics response. 
Bragi currently sets a `Content-Type: application/json` header on this endpoint, which is incorrect as the prometheus metrics are plain text.
=> bragi: Follow best practices for prometheus metrics endpoint

scripts/import2mimir.sh
For portability /usr/bin/bash should not be used: it does not exist on
most *nixes (instead it is /bin/bash on most Linuxes). /usr/bin/env bash
can be run on most *nixes including BSD families and Linuxes.
See: https://stackoverflow.com/a/10383546/73673
=> Change hardcoded -broken- bash path for *nixes

src/bin/osm2mimir.rs
When importing OSM, streets were parsed and extracted regardless of whether or not they were needed.
This patch puts all the street parsing and extracting in the conditional that checks for `--import-way`. 
On imports with `osm2mimir` that don't have `--import-way` set, this greatly improves performance. Especially on OSM files with lots of streets (obviously).
Here's a rough timer ran on before and after the patch. CPU-time improved by 33%.
```
148M mei  5 02:03 /mnt/sda/OSM/mimir/osm/netherlands-gelderland-latest.osm.pbf
before:
time RUST_LOG=error ./target/release/osm2mimir --dataset=nl --input /mnt/sda/OSM/mimir/osm/netherlands-gelderland-latest.osm.pbf --poi-config ./poi_config.json --import-poi
real	1m54,401s
user	2m36,302s
sys	0m8,153s
after:
time RUST_LOG=error …
```
=> Don't parse and extract streets if we don't import ways.

libs/mimir/src/rubber.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs
Send `bulk_index`'s batches in parallel. The number of threads can be defined in a distinct CLI parameter `-T`.
Note that when the number of threads is too high (eg. `-T=16` on my local tests), Elasticsearch may crash during the import (the max number of threads is probably related to the number of shards?). Thus, the default number of threads is set to 1 in order to make sure that the caller sets the right amount.
Performances
---
Here are some benchmarks obtained by importing OpenAddresses data for Denmark (~3M8 addresses) using openaddresses2mimir.
(my CPU already struggles at `--nb-insert-threads=2`, I can't get any better result).
|    branch   |      |
|:-----------:|-----:|
|    master   | 5:29 |
| HEAD (-T 1) | 5:35 |
| HEAD (-T 2) | 4:33 |
I tried to distribute the CPU stress of …
=> send batches from several threads in Rubber's bulk_index

.travis.yml, docker/Dockerfile_bragi, docker/Dockerfile_import
Automated build of the docker image using Rust 1.39 where failing since https://github.com/CanalTP/mimirsbrunn/pull/385.
While I was on it I updated everything to 1.44 (latest stable version).
=> update docker images to rust 1.44

Cargo.lock, Cargo.toml, build.rs, libs/bragi/Cargo.toml, libs/bragi/build.rs, libs/bragi/src/lib.rs, libs/bragi/src/routes/status.rs
We are currently using a build hook for Bragi that overrides the version number specified in `Cargo.toml`. The same behavior is implemented for the top-level package but I don't think we actually take benefit of it.
I think it is a rather heavy behavior to keep as it implies that cargo will rebuild all binaries at each invocation, which is rather slow.
=> Stop overriding package version at compile time

config/bragi-settings.toml, libs/bragi/src/query.rs, libs/bragi/src/query_settings.rs, libs/bragi/src/routes/autocomplete.rs
Add query parameters `proximity_scale`, `proximity_offset` and `proximity_decay` which allows to tweak the weight computed from the distance in proximity queries.
These parameters reflect the parameters used by Elasticsearch itself. See [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-decay) for more details.
The score of such a query is computed from the distance of documents to input `lat`/`lon` based on a gaussian distribution:
[![](https://www.elastic.co/guide/en/elasticsearch/reference/current/images/decay_2d.png)](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_supported_decay_functions)
Currently, this score function is the same for all queries, only tweakable …
=> allow to change the radius of proximity queries

libs/mimir/src/rubber.rs
This PR fixes an issue we have in production where updating a coverage may accidentally delete another unrelated coverage.
The name of the coverage is embedded in the alias. If you have a coverage 'foo', then the alias will start with 'munin_foo'.
Now, if you have another coverage 'foo_bar', it will start with 'munin_foo_bar'. When you update 'foo', it will probably delete
'munin_foo' and 'munin_foo_bar'.
Warning (this PR is based on a branch 'update_dependencies')
=> Prevent unwanted alias removal

Cargo.lock, config/bragi-settings.toml, libs/bragi/src/query.rs, libs/bragi/src/query_settings.rs, libs/mimir/src/rubber.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/osm_reader/street.rs
https://github.com/CanalTP/mimirsbrunn/pull/417 introduced a way to apply a very slight proximity boost for a very large region. However it kept the previous behavior of using different weights in a proximity context and out of a proximity context, this makes it hard to benefit from the feature as some proximity-specific behaviors would raise for quite generic requests (eg. decreasing the importance of the weight consequently).
This PR addresses the issue by computing a smooth transitions of the weights used to build ES queries when the radius changes:
- the new setting `radius_range` gives an interval for this behavior of "transition" base on the value of `curve.offset + curve.scale`
- if `curve.offset + curve.scale` is above `radius_range`, we use weights from `max_radius_fuzzy` or …
=> Progressive focus

config/bragi-settings.toml, libs/bragi/src/query.rs, libs/bragi/src/query_settings.rs
This is a correction for two changes from https://github.com/CanalTP/mimirsbrunn/pull/423:
1. There was a confusion between `max_radius` and `min_radius` settings that were not consistent with previous settings: a large radius correspond with a flexible use of the focus, which is closest to what `no_coord` was (and vice-versa for `min_radius` and `coord`)
2. We were reducing the impact of the proximity for large radius [here](https://github.com/CanalTP/mimirsbrunn/compare/master...remi-dupre:fix-progressive-focus?expand=1#diff-1ac92e7119dffce18713ecd2b8626802L290) which doesn't seem really relevant. The proximity will already not penalize many POIs because the radius is so large, so this behavior mostly made the proximity part useless with larger zoom.
=> Fix progressive focus

libs/mimir/src/objects.rs
[This is probably a new clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro) which made me discover the `matches!` macro, it makes things slightly simpler.
=> mimir: use matches! macro

Cargo.lock, Cargo.toml, config/default.toml, config/kisio.toml, docker/Dockerfile_import, scripts/autocomplete.sh, scripts/import2mimir.sh, src/bin/osm2mimir.rs, src/lib.rs, src/osm_reader/street.rs, src/settings.rs, tests/bragi_filter_types_test.rs, tests/bragi_osm_test.rs, tests/bragi_poi_test.rs, tests/bragi_postcode_test.rs, tests/bragi_stops_test.rs, tests/bragi_synonyms_test.rs, tests/bragi_three_cities_test.rs, tests/canonical_import_process_test.rs, tests/osm2mimir_bano2mimir_test.rs, tests/osm2mimir_test.rs
This patch introduces 2 new CLI arguments for osm2mimir:
-  `--config-dir` to point to a directory where configuration are stored
-  `--settings` to identify custom settings.
The motivation is to have different settings depending on the context.
It uses these new settings to expand the list of invalid highways.
It introduces a new dependency, [config](https://docs.rs/config/0.10.1/config/), to read a `.toml` file.
This config crate has possibly many functionalities, like merging configuration files (like specific settings, on top of default ones),
overwriting values with environment variables, ...
=> [FEAT]: Add custom settings for osm2mimir

libs/mimir/src/rubber.rs, src/addr_reader.rs, src/bin/ntfs2mimir.rs, src/bin/osm2mimir.rs
This is a stopgap fix to retrieve the error context in some situation
where it was dropped and not displayed to the user. This may not be
the way failure was meant to be used (rather using error chains), but
this solution gets the error context to the end user. A long term
solution will involve changing to eg anyhow, snafu or other error
libraries
=> [FIX]: Display error in context

Cargo.lock, Cargo.toml, libs/bragi/Cargo.toml, libs/mimir/Cargo.toml, libs/mimir/src/rubber.rs, src/osm_reader/street.rs
This patch adds a warning in the logs for each stop which result in an insertion error from Elasticsearch (and for which Elasticsearch returns error information)
=> [FEAT]: Make use of BulkResult

libs/mimir/src/rubber.rs
Fixes #432 
As is, it reverts to the original behavior (before #431) where any error will stop the bulk index, while keeping an explicit error message instead of relying on rs-es panicking.
`max_bulk_errors` value could then be used by importers that would need some sort of error tolerance.
=> Define max_bulk_errors in Rubber, with 0 as default value

.make-release-support, Makefile, README.md, config.env, deploy.env, docker/Dockerfile_bragi, docker/Dockerfile_import
To support multiple platforms (like debian buster and stretch), we
introduce build arguments (`--build-arg`) when calling Dockerfile, such
that one Dockerfile can be used to generate one image per debian
platform.
In addition we introduce a Makefile and support script to facilitate
releases.
Building a docker image, you now have to use a line like:
docker build --build-arg DEBIAN_VERSION=buster --build-arg RUST_VERSION=1.47 ...
Plus de details sur le Makefile [ici](https://github.com/crocme10/test-makefile)
=> [FEAT]: Add Makefile and parametric dockerfiles

.github/workflows/debian.yml
This pull request introduces rust toolchain versions adapted to the platform on which the build is ran.
=> [Fixed] Use old toolchains for old platform

docker/bragi/Dockerfile, docker/mimirsbrunn/Dockerfile
New version of the Dockerfile. This one uses cache optimization using the two-stage pattern.
Due to the presence of both binaries and libraries, we have to create dummy files.
If this version is ok with you, I'll do the same with `docker/bragi/Dockerfile`
=> [Fixed] loosing Cargo.lock in Dockerfile

.make-release-support, Makefile, deploy.env
This is a significant change in the Makefile. It should now support:
* Multiple docker images: Each image is a subdirectory under the docker directory at the root.
* Multiple docker repositories: One for each of the three main target: snapshot, prerelease, and release. These repositories are configured in the deploy.env file, with corresponding variable names: SNAPSHOT_REPO, RELEASE_REPO, ...
=> Multiple docker repo

Cargo.lock, Cargo.toml, libs/bragi/src/query.rs, libs/bragi/src/routes/autocomplete.rs, libs/mimir/src/objects.rs, scripts/autocomplete.sh, src/bin/poi2mimir.rs, src/osm_reader/osm_store.rs
This PR fixes some lints (clippy), and adds an optional `request_id` parameter, which can be used to trace requests. This probably is a moot issue if we overhaul tracing in a distributed environment with more efficient tools (eg jaeger, ....)
=> request-id

scripts/build_deb.sh
Adds a `--locked` option to cargo install so that we use the crates found in Cargo.lock, and we don't try to update them to newer versions if available.
=> Add locked option to cargo install

.github/workflows/workflow.yml
This version fixes the previous version which was not overriding the toolchain version.
It does not call the makefile, but rather relies solely on the github actions.
=> Fix CI workflow

libs/mimir2/src/adapters/secondary/elasticsearch/mod.rs, libs/mimir2/src/utils/docker.rs, src/bin/cosmogony2mimir.rs
Try to detect early if there is a connection problem when starting an elasticsearch docker. This improves the testing situation since we won't get the mutex guard if elasticsearch is not ready.
=> Fix docker connectivity

libs/mimir2/src/domain/model/document.rs, libs/mimir2/src/domain/model/error.rs, libs/mimir2/src/domain/model/mod.rs, libs/mimir2/src/domain/ports/primary/list_documents.rs
* `ListDocuments` becomes `ListDocuments<D>` which returns a `Stream` on the entry type.
* The type parameter `D` must implement `ContainerDocument`
* `list_documents` use a new `domain::model::error::Error` which will be common to all primary ports
=> ListDocuments: take document type as parameter and use public error type

src/bin/cosmogony2mimir.rs
Tests had been commented out while trying to restore Github Actions status. Now that the problem responsible for failing tests has been identified and fixed, we can add those tests.
=> Restore tests for cosmogony2mimir

libs/mimir2/src/domain/model/error.rs, libs/mimir2/src/domain/ports/primary/explain_query.rs, libs/mimir2/src/domain/ports/primary/generate_index.rs, libs/mimir2/src/domain/ports/primary/list_documents.rs, libs/mimir2/src/domain/ports/primary/search_documents.rs, libs/mimir2/src/domain/ports/secondary/list.rs
This PR extends `domain/model/error`, and ensures that all primary ports use this type in their interface. This prevents leaking secondary ports error types to primary interfaces.
=> Primary Ports use model::error

libs/mimir/src/objects.rs, tests/poi2mimir_test.rs
POI have a field 'poi_type', and the poi_type has in turn two fields,
'id' and 'name'. This change makes sure that poi_type.id is prefixed
with 'poi_type'.
=> Add poi_type to poi's poi_type

Cargo.lock, src/osm_reader/admin.rs
Code INSEE must be 5 characters. It is not clear why the code was previously trimmed when it started with zeros.
=> remove trimming of insee code

Makefile, libs/common/src/document.rs, libs/mimir2/src/adapters/secondary/elasticsearch/configuration.rs, libs/mimir2/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir2/src/adapters/secondary/elasticsearch/mod.rs, libs/mimir2/src/adapters/secondary/elasticsearch/storage.rs, libs/mimir2/src/domain/model/configuration.rs
Update the `make check` command so that it takes into account all the workspaces.
Provide a bit more context in some error cases, especially during the creation of the configuration of an elasticsearch index.
Modify elasticsearch adapter tests to make sure they pass.
=> Update elasticsearch test with new configuration.

libs/common/src/config.rs, src/addr_reader.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/openaddresses2mimir.rs, src/utils.rs
This just adds a binary for bano similar to `openaddresses2mimir` which was added in https://github.com/CanalTP/mimirsbrunn/pull/510.
I deduplicated the config loading logic but there is still a lot of similarities between implementations of the importers.
=> ES7: add bano2mimir

libs/mimir2/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir2/src/adapters/secondary/elasticsearch/storage.rs
Fixes #494 
`add_alias` and `remove_alias` methods are replaced with `update_alias`, relying on the Aliases API:  
https://www.elastic.co/guide/en/elasticsearch/reference/7.14/indices-aliases.html#indices-aliases
=> ES aliases: Use atomic update instead of successive add and remove

.github/workflows/create_publish_bragi_docker.yml, .github/workflows/release.yml, .github/workflows/workflow.yml, Cargo.lock, Cargo.toml, Makefile, config/bragi/default.toml, docs/bragi.md, docs/concepts.md, docs/tbl/autocomplete-query-param.md, libs/mimir2/Cargo.toml, libs/mimir2/src/adapters/primary/bragi/api/mod.rs, libs/mimir2/src/adapters/primary/bragi/handlers/mod.rs, libs/mimir2/src/adapters/primary/bragi/routes/mod.rs, libs/mimir2/src/adapters/secondary/elasticsearch/mod.rs, libs/mimir2/src/utils/docker.rs, libs/places/Cargo.toml, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bragi/settings.rs, src/osm_reader/admin.rs, tests/admin.rs, tests/poi2mimir_test.rs
`serial-test` is a light-weight dependency that will take in charge the mutex and avoid poisoning on failure.
Tests with `#[serial]` will run sequentially.
It's also possible to use `#[serial(something)]` to define independent sequences:
https://docs.rs/serial_test/0.5.1/serial_test/attr.serial.html
=> Use 'serial_test' to run tests sequentially, remove mutex on docker init

config/elasticsearch/addr/settings.json, config/elasticsearch/admin/settings.json, config/elasticsearch/poi/settings.json, config/elasticsearch/stop/settings.json, config/elasticsearch/street/settings.json, features/addresses/limousin.feature, tests/data/bano/limousin.csv
~:warning: this is based on #537 which requires to be merged first. It can still be reviewed on looking at f247ae8 alone.~
Enable synonyms filters in mappings. They were already defined in #529 so there is not much to do :smiley:
=> Enable synonym filter

libs/mimir2/Cargo.toml
This appears to be what is breaking [the CI](https://github.com/CanalTP/mimirsbrunn/runs/4089978246?check_suite_focus=true) in master. It can also be an issue if some project depends on `mimir2`.
=> enable `serde` feature for `url` in mimir2

src/bragi/server.rs, src/utils/logger.rs
Currently we have a default RUST_LOG string which includes `mimir=debug`. This is not necessary, and this PR changes that to `mimir=default`
=> increase default mimir log level

config/ctlmimir/default.toml, config/ctlmimir/testing.toml, src/settings/ctlmimir.rs
`config/ctlmimir` seems redundant with `config/logging`, so I'm not sure we should maintain both.
=> ctlmimir: use config/logging for logging.path definition

docker/run_with_default_config.sh
Currently the docker images always exit with code 0, which is the exit code of bunyan. This means that errors would hardly be programmatically detected, eg. during import pipelines.
To reflect mimir's exit code we have to tweak a bit how the pipe is handled, this can be done with a `set -o pipefail` in bash, according to [the documentation](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html):
```
pipefail
If set, the return value of a pipeline is the value of the last (rightmost) command
to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.
This option is disabled by default.
```
=> propagate exit code for docker images

docker/mimirsbrunn/Dockerfile
This will help with layered caching mechanisms as some of the copies (essentially `tests/`) takes some time to perform.
=> reorder docker copies with most commonly modified at the end

Cargo.lock, Cargo.toml, libs/tests/src/bano.rs, src/addr_reader.rs, src/bin/bano2mimir.rs, src/bin/openaddresses2mimir.rs, src/utils/fs.rs, src/utils/mod.rs
I initially just wanted to add extra logs in the address importers which was failing silently, eg. when using an invalid file path, but I think there was a few other issues we wanted to handle.
Here is what changed:
- added a tracing instrument for each input file, log when there is an issue with deserializing the CSV into a "record" (before calling `into_addr`), log when there is an issue with opening a file
- de-duplicated addr parsers: there was two separate co-existing implementations, one for bano (close to what was there before async) and one for openaddresses
- one of the implementations didn't support gzip files, I re-implemented the decoder using `async-compression` (which still uses `flate2` as a back-end)
- when specifying a directory as input, we will walk recursively instead …
=> address importers rationalization

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/domain/model/stats.rs
I initially wanted to showcase #625, but it turns out that the stats that we compute in ES internals are very simple (just two integers), so we could just use a `fold` to collect concurrently computed stats instead of using a mutex.
=> insertion stats don't require an `Arc<Mutex<...>>`

config/osm2mimir/default.toml
There's just a typo in default configuration, as this is configurable anyway I don't think this requires extending testing.
=> default container name for streets should be `street`

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/storage.rs, libs/mimir/src/domain/ports/primary/configure_backend.rs, libs/mimir/src/domain/ports/primary/generate_index.rs, libs/mimir/src/domain/ports/secondary/storage.rs
The constraint was previously enforced by automock, but this is finally not the direction we took for tests.
This relaxing will allow to attach some context to the input stream, an application of this that lead me to this suggestion was the collection of statistics:
```rust
let mut count_errors = HashMap::new();
let pois = read_pois(raw_xml, admin_geofinder).filter_map(|poi| {
future::ready({
poi.map_err(|err| *count_errors.entry(err).or_insert(0) += 1)
.ok()
})
});
create_index(
&mimir_es,
&raw_config,
&settings.container_tripadvisor.dataset,
IndexVisibility::Private,
pois,
)
.await
.expect("error while indexing POIs");
```
In this example, the stream `pois` only lives as long as `count_errors`, which is not static.
=> allow to index from streams of any lifetime

libs/mimir/src/adapters/primary/common/settings.rs, src/addr_reader.rs, src/osm_reader/mod.rs
Rust's [`File`](https://doc.rust-lang.org/std/fs/struct.File.html) doesn't have any buffer by default, this is generally more efficient and good practice to use some,
=> wrap buffers arround file readers

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/models.rs, libs/mimir/src/adapters/secondary/elasticsearch/storage.rs, libs/mimir/src/domain/model/error.rs, libs/mimir/src/domain/model/mod.rs, libs/mimir/src/domain/model/update.rs, libs/mimir/src/domain/ports/primary/generate_index.rs, libs/mimir/src/domain/ports/secondary/storage.rs, libs/mimir/src/lib.rs, libs/mimir/src/tests/generate_and_update.rs, libs/mimir/src/tests/mod.rs
The adds a more flexible API to the `generate_index` ports which allows to update documents before publishing it. This is very targeted for our use-case using mimir as a library, where we need to import data from tripadvisor which are split into different datasets: https://github.com/Qwant/fafnir/pull/71.
This new API can be called with a chain of methods, like that:
```rust
client.init_container(&container_config)
.await?
.insert_documents(doc_stream1)
.await?
.insert_documents(doc_stream2)
.await?
.update_documents(update_stream)
.await?
.publish() // there is even a warning if this last call is forgotten
.await?;
```
The `generate_index` method is still there, I think it is still relevant as a shortcut for the new API as it will group all potential failure points in a single call. …
=> Add port to update documents before publishing

Cargo.lock, Cargo.toml, libs/common/Cargo.toml, libs/common/src/config.rs, libs/mimir/Cargo.toml, libs/mimir/src/adapters/primary/templates.rs, libs/mimir/src/adapters/secondary/elasticsearch/mod.rs, libs/mimir/src/utils/docker.rs, libs/places/Cargo.toml, libs/tests/Cargo.toml, src/osm_reader/poi.rs, src/settings/bano2mimir.rs, src/settings/cosmogony2mimir.rs, src/settings/ctlmimir.rs, src/settings/ntfs2mimir.rs, src/settings/openaddresses2mimir.rs, src/settings/osm2mimir.rs, src/settings/poi2mimir.rs
Config has introduced a few breaking changes on master so now it can be a bit painful if cargo decides to update it.
Instead of pinning a specific commit I think it is time to rely on the published version, which is quite recent (0.11).
=> update to stable config from crates.io

.jenkins/release
This PR update the Jenkins release flow because of the breaking change. 
Now, we just need to change the main _cargo.toml_ version to release.
=> CI: Update Jenkins flow for ES7 Release

.jenkins/release
Following the https://github.com/CanalTP/mimirsbrunn/pull/656 job, the migration with _Github App_ is needed to respect the security policy.
=> CI: Update Jenkins credential with Github App

docker/bragi/Dockerfile, docker/run_with_default_config.sh, src/settings/ctlmimir.rs
This makes a few changes to the ergonomic of docker images:
- make `--config-dir` and `--run-mode` overridable through env
- make it possible to disable bunyan formatting through env
- use `run_with_default_config` for Bragi to interact with it the same way as other mimirsbrunn utils
- remove env overrides in Bragi image, which was redundant with default config files
- changed environment prefix from `CTLMIMIR_` to `MIMIR_` for ctlmimir, this is consistent with importers, only still has a different prefix (is that fine? there may  have been a motivation?)
=> Docker images stabilization

benches/searching.rs, libs/mimir/src/adapters/primary/bragi/api.rs, libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/primary/common/dsl.rs, libs/mimir/src/adapters/primary/common/filters.rs, libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/query.rs, libs/mimir/src/domain/ports/primary/search_documents.rs, libs/mimir/src/domain/ports/secondary/search.rs, libs/mimir/src/utils/deserialize.rs, src/bin/openaddresses2mimir.rs, src/bin/query.rs, src/osm_reader/poi.rs, src/pois.rs, tests/steps/search.rs
If a "timeout=2000" is present in the query made to bragi, use this timeout value for querying elasticsearch (instead of the default one in the config)
=> Parse timeout in autocomplete query

benches/searching.rs, libs/mimir/src/adapters/primary/bragi/api.rs, libs/mimir/src/adapters/primary/bragi/gql.rs, libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/primary/bragi/routes.rs, libs/mimir/src/adapters/primary/common/dsl.rs, libs/mimir/src/adapters/primary/common/filters.rs, libs/mimir/src/adapters/secondary/elasticsearch/query.rs, libs/mimir/src/domain/ports/primary/search_documents.rs, libs/mimir/src/domain/ports/secondary/search.rs, src/bin/openaddresses2mimir.rs, src/bin/query.rs, src/osm_reader/poi.rs, src/pois.rs, tests/steps/search.rs
- When `pt_dataset[]=idfm&type=public_transport:stop_area` is specified in an autocomplete query, then bragi will search only in the elasticsearch index `munin_stops_idfm`, and not in other `munin_stop_*` indices. If not `pt_dataset` is specified, it will search in `munin_stops` which is an alias for all `munin_stop_*` indices.
- When `poi_dataset[]=idfm&type=poi` is specified in an autocomplete query, then bragi will search only in the elasticsearch index `munin_poi_idfm`, and not in other `munin_poi_*` indices. If not `poi_dataset` is specified, it will search in `munin_pois` which is an alias for all `munin_poi_*` indices.
This should provide the functionality wanted in https://github.com/CanalTP/mimirsbrunn/pull/652
=> Allow pt_dataset and poi_dataset in bragi autocomplete query

config/bano2mimir/default.toml, config/bragi/default.toml, config/cosmogony2mimir/default.toml, config/ntfs2mimir/default.toml, config/openaddresses2mimir/default.toml, config/osm2mimir/default.toml, config/poi2mimir/default.toml, libs/common/src/config.rs, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/ctlmimir.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/poi2mimir.rs, src/bragi/server.rs, src/bragi/settings.rs, src/settings/bano2mimir.rs, src/settings/cosmogony2mimir.rs, src/settings/ctlmimir.rs, src/settings/ntfs2mimir.rs, src/settings/openaddresses2mimir.rs, src/settings/osm2mimir.rs, src/settings/poi2mimir.rs
This PR allow variable like "nb_thread" to be set by an env var with underscore character ->  BRAGI_NB_THREADS. 
So now to set for example ES URL we have to use the following env var : 
BRAGI_ELASTICSEARCH__URL instead of BRAGI_ELASTICSEARCH_URL previously
=> Change Var Env separator

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/models.rs
Example:
**PUT test_coord**
``` json
{
"mappings": {
"properties": {
"approx_coord": {
"type": "geo_shape",
"precision": "5m"
}
}
}
}
```
Post invalid geo_shape
**POST _bulk**
``` json
{ "index" : { "_index" : "test_coord", "_id" : "1" } }
{"text": "Geopoint as an object","approx_coord": {    "type" : "point",    "coordinates" : [-7703653, 38.897676]}}
```
result:
``` json
{
"took" : 0,
"errors" : true,
"items" : [
{
"index" : {
"_index" : "test_coord",
"_type" : "_doc",
"_id" : "1",
"status" : 400,
"error" : {
"type" : "mapper_parsing_exception",
"reason" : "failed to parse",
"caused_by" : {
"type" : "invalid_shape_exception",
"reason" : "Bad X value -7703653.0 is not in boundary Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)"
}
}
}
}
]
}
```
Result in log file:
=> Display more informations bulk insert

benches/searching.rs, libs/mimir/src/adapters/primary/bragi/api.rs, libs/mimir/src/adapters/primary/bragi/autocomplete.rs, libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/primary/common/dsl.rs, libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, src/bin/query.rs, src/bragi/server.rs, tests/steps/search.rs
Reproduce in ElasticSearch7 what Bragi, with ES2, was doing for the `prefix` autocomplete part.
=> Reproduce bragi prefix autocomplete search

libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/primary/common/dsl.rs
Since the "boundary" field is quite heavy, and not used in bragi anyway, we ask Elasticsearch to *not* include it in its responses.
The  "boundary" field is still included by Elasticsearch in the queries made in *2mimir
=> Remove "boundary" field from Elasticsearch's responses to bragi

libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/secondary/elasticsearch/internal.rs
The `request_timeout()` is just setting a timeout after which, if bragi did not receive an http response from ES, an http error is returned from `.send()`.
Here I try different settings to limit the time spent in elasticsearch.
Some docs :
https://www.elastic.co/guide/en/elasticsearch/reference/7.15/search-search.html 
https://docs.rs/elasticsearch/7.14.0-alpha.1/elasticsearch/struct.Search.html#
=> Control time spent in elasticsearch

libs/mimir/src/adapters/primary/bragi/handlers.rs
On autocomplete endpoint, when no answer is found, return :
```
type	"FeatureCollection"
geocoding	
version	"0.1.0"
query	""
features	[]
```
Reverse endpoint should already return this answer
=> Fix empty answer autocomplete

config/elasticsearch/templates/components/mimir-base.json, config/elasticsearch/templates/components/mimir-dynamic-mappings.json
`Search_as_you_type` type is not using character tokenizer for his `_2gram` and, `_3gram` subfield.
The goal of this PR is to use the previous mapping used in ES2.
=> Remove `search_as_you_type` field to use previous mapping

libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/primary/common/dsl.rs
Geocodeur test works better + performance enhanced compared to search_as_you_type + autocomplete working better (on very few manual tests)
=> Reproduce Bragi2 autocomplete

docker/bragi/Dockerfile, docker/mimirsbrunn/Dockerfile, docker/run_with_default_config.sh
As it is not used anymore, we don't need to bloat docker images with node/npm/bunyan :slightly_smiling_face:
=> Docker remove bunyan

libs/tests/src/osm.rs, src/addr_reader.rs, src/bin/osm2mimir.rs, src/pois.rs
We just removed all confusing 'buffered' & 'buffer_unordered' functions because tasks were not running asynchronously !!! 
To run async tasks with  'buffered' & 'buffer_unordered' functions  please use tokio::spawn. 
The number of function running in // is up to tokio runtime (cf config nb_threads)
=> Fix nb_threads xxx2mimir

libs/mimir/src/adapters/primary/bragi/handlers.rs
Autocomplete search in Poi OSM index by default (with streets, admin and addresses)
=> Search in Poi OSM index by default

libs/mimir/src/adapters/primary/bragi/handlers.rs
Search in Poi OSM index by default and search in  poi_dataset[] ONLY if specified
=> Search in Poi OSM by default and only in poi_dataset[] is specified

config/bano2mimir/default.toml, config/cosmogony2mimir/default.toml, config/ntfs2mimir/default.toml, config/openaddresses2mimir/default.toml, config/osm2mimir/default.toml, config/poi2mimir/default.toml, src/bin/bano2mimir.rs, src/bin/cosmogony2mimir.rs, src/bin/ctlmimir.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/poi2mimir.rs, src/settings/bano2mimir.rs, src/settings/cosmogony2mimir.rs, src/settings/ntfs2mimir.rs, src/settings/openaddresses2mimir.rs, src/settings/osm2mimir.rs, src/settings/poi2mimir.rs, src/utils/mod.rs, src/utils/template.rs
In ES7, the function to update components and templates for each type of data (poi, ntfs, bano...) is separated and is ctlmimir.
Instead of executing ctlmimir each time to update components and templates if there is any modifications, this function is also called if configured while indexing any type of data.
To activate update of components and templates, add 'update_templates = true' in /config/xx2mimir/default.toml
Without any modification of configuration, it should work as before.
=> If configured, each indexing should update all components and templates

libs/mimir/src/adapters/primary/bragi/api.rs, libs/mimir/src/adapters/primary/bragi/handlers.rs
Due to a limitation in serde_qs, you need to explicitly specify how you parse a field after a layer of #[serde(flatten)], this is what is already done for some existing fields in the autocomplete parameters.
However I don't think this workarround would work for two layers of flatten, so the simplest fix is probably to repeat the parameters definition.
Btw, the error it fixes:
```
$ curl "https://bragi.prod-maps.c4.par1.kube.qwant.ninja/api/v1/autocomplete-explain?q=bruge&lon=2.40&lat=48.90&doc_id=osm:node:1729160206&doc_type=poi"
{"short":"validation error","long":"failed with reason: invalid type: string \"48.90\", expected f32"}
```
=> fix non-string parameters for autocomplete-explain endpoint

Makefile, benches/searching.rs, libs/mimir/src/adapters/primary/bragi/handlers.rs, libs/mimir/src/adapters/primary/bragi/prometheus_handler.rs, libs/mimir/src/adapters/primary/common/dsl.rs, src/bin/query.rs, tests/steps/search.rs
This was a metric that was computed for the ES2 branch and will be useful to debug were the time is spent during computation.
=> re-implement metric `bragi_elasticsearch_request_duration_seconds`

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/models.rs
This was due to a naïve check `json["_shards"]["successful"] == 1` that was probably written in an early stage and never tested after that.
I couldn't find any documentation of the result format of the [forcemerge API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-forcemerge.html), so I just catched the success/failure/total counters that I can observe in practice.
=> fix forcemerge failing when there is more than a single shard

libs/mimir/src/adapters/secondary/elasticsearch/storage.rs, libs/mimir/src/domain/model/update.rs, libs/mimir/src/domain/ports/primary/generate_index.rs, libs/mimir/src/domain/ports/secondary/storage.rs, libs/mimir/src/tests/generate_and_update.rs
For some reason when using a dot-sparated key chain to update a document
value, elasticsearch will attempt to update the mapping. Which conflicts
with `properties` which is flattened.
For example the following update operation fails:
```json
{
"script": {
"source": "ctx._source['properties.image'] = \"test\""
}
}
```
> Could not dynamically add mapping for field [properties.image]. Existing mapping for [properties] must be of type object but found [flattened].
And the following one succeeds
```json
{
"script": {
"source": "ctx._source['properties']['image'] = \"test\""
}
}
```
So the approach of this PR is to manually split key and subkeys and
generate the subtree for ES to update:
```json
{
"doc": {
"properties": {
"image": "test"
}
}
}
```
EDIT: And it also gets rid of the use of …
=> doc updates: better support for dot-separated keys

.github/workflows/sonarcloud.yml
We don't need a Sonarcloud analysis on `dependabot` PR since they do not change anything about tests and code (so no coverage change).
=> ci: ignore sonarcloud analysis for 'dependabot'

docker/bragi/Dockerfile
In order to be able to do some `healthcheck` inside Docker, we need some way to query the `/status` API from inside the docker image. Note that this solution is not ideal since `curl` is not necessary for `bragi` and therefore, it adds a dependency inside that image (and therefore, possibly some attack surface). [But one of the alternative is not necessarily easier](https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/).
ref: NAV-1358
=> feat: add 'curl in bragi's docker image

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/models.rs, libs/mimir/src/domain/model/stats.rs
On some corner cases we can get the following error while updating documents:
```
thread 'main' panicked at 'Error inserting chunk: JSON Elasticsearch Deserialization Error: error decoding response body: unknown variant `noop`, expected one of `created`, `updated
```
=> internals: avoid crash when ES bulk returns NoOp status

.github/workflows/docker.yml, .github/workflows/sonarcloud.yml, README.md, sonarcloud.yml
We are currently experimenting working on a fork of mimirsbrunn, which we would keep up to date with mimirsbrunn but in which we could operate more freely (eg. merging before you had time to review in order to deploy).
This PR proposes a change to make the CI work on several repos:
-  replacing the hardcoded "navitia" org with a secret value (ie. you would need to add DOCKER_ORG=navitia in the secrets before merging this PR)
- push docker images for branches and use the branch name as label, just for convenience
=> Update docker CI to be compatible with forks

config/bano2mimir/default.toml, config/ntfs2mimir/default.toml, config/openaddresses2mimir/default.toml, config/osm2mimir/default.toml, config/poi2mimir/default.toml, libs/tests/src/ntfs.rs, src/admin.rs, src/admin_geofinder.rs, src/bin/bano2mimir.rs, src/bin/ntfs2mimir.rs, src/bin/openaddresses2mimir.rs, src/bin/osm2mimir.rs, src/bin/poi2mimir.rs, src/pois.rs, src/settings/admin_settings.rs, src/settings/bano2mimir.rs, src/settings/mod.rs, src/settings/ntfs2mimir.rs, src/settings/openaddresses2mimir.rs, src/settings/osm2mimir.rs, src/settings/poi2mimir.rs, src/stops.rs
Ntfs2mimir needs data about the administrative regions to enrich the stops before putting them into elasticsearch.
The data about the administrative regions  was collected from elasticsearch. 
This collection method causes a non-negligible load on elasticsearch, resulting in various timeouts and errors in bragi.
This PR adds the option to collect the data about administrative region from a local cosmogony file (the same file used to build the "admin" index in cosmogony2mimir).
If a "cosmogony_file" is configured in ntfs2mimir config file, then this file will be used. 
If such configuration is not present, ntfs2mimir will gather administrative regions from elasticsearch, as before.
The same thing is done for the binaries osm2mimir, openaddresses2mimir and poi2mimir.
For more details: …
=> [ntfs2mimir] attach admins from file

config/osm2mimir/default.toml, config/poi2mimir/default.toml, libs/mimir/src/utils/deserialize.rs, libs/tests/src/osm.rs, src/bin/osm2mimir.rs, src/osm_reader/poi.rs, src/pois.rs, src/settings/osm2mimir.rs, src/settings/poi2mimir.rs
For POI integration, make max-distance configurable on address reverse-search.
This maximum defaults to 1000 m now, same as before for `osm2mimir`.
For `poi2mimir`, it was 50 m previously (too short in some cases).
Related to internal ticket: https://navitia.atlassian.net/browse/NAV-1383
:heavy_check_mark: Hand-tested that this corrects our precise cases
:heavy_check_mark: This does not seem to impact integration perfs for `poi2mimir` (although machine used to test is slow by default)
Bonus #codesmell: removed 2 `automagic` occurrences :tada:
=> [poi2mimir/osm2mimir] configurable max-distance on address reverse-search for POI

libs/mimir/src/adapters/primary/bragi/prometheus_handler.rs
A minima, we should increment the number, not decrement it.
And let's use an integer gauge that is susceptible to get better performance (see [documentation](https://docs.rs/prometheus/latest/prometheus/type.IntGauge.html)).
Also, `Gauge` uses `AtomicF64` that implement increment with [a fallible addition](https://docs.rs/prometheus/0.13.0/src/prometheus/atomic64.rs.html#112).
`IntGauge` uses `AtomicI64` which itself use [`std::sync::atomic::AtomicI64::fetch_add`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicI64.html#method.fetch_add): `fetch_add` does not panic but [wraps on overflow](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicI64.html#method.fetch_add).
=> feat: use an integer gauge for counting request in flight

libs/mimir/src/adapters/secondary/elasticsearch/internal.rs, libs/mimir/src/adapters/secondary/elasticsearch/storage.rs, libs/mimir/src/domain/ports/primary/configure_backend.rs, libs/mimir/src/domain/ports/primary/generate_index.rs, libs/mimir/src/domain/ports/secondary/storage.rs
This doesn't change anything here (except maybe for a bit of
simplification) but it makes mimir more flexible as a library in other
repos.
=> remove Send + Sync on streams

.github/workflows/release.yml, .github/workflows/release7.yml
We will eventually upgrade Debian version to up-to-date Debian versions (probably Debian 11). But this is going to be part of a larger effort.
At the moment, let's fix it as in [`navitia`](https://github.com/hove-io/navitia/pull/3859) and [`navitia-docker-compose`](https://github.com/hove-io/navitia-docker-compose/pull/147).
=> ci: force installation on old Debian versions

.github/workflows/docker.yml
Using single quotes `'`, the string `$GITHUB_REF_NAME` was not evaluated and was sent as is to `hove-io/bragi-aws-assets` which actually inserted it in Bash and evaluated it as `main` (the name of the default branch in `hove-io/bragi-aws-assets`), provoking a `docker pull bragi:main` which didn't exist, obviously. Note that using `${{ ... }}` should be evaluated before everything, as this is the Github Actions templating language.
=> ci: use evaluated environment variable instead of raw

.github/workflows/release.yml, .github/workflows/release7.yml
This Jenkins job was triggered to gather Debian packages artifacts and push them to an FTP for further deployments. We do not need that anymore (deployment changed).
=> ci: remove jenkins jobs

libs/mimir/src/adapters/primary/bragi/routes.rs, src/utils/logger.rs
Will give the ability to deactivate ANSI formatting (give some coloring and bold for example) when necessary (see screenshot below with all the `[2m` and other `[32m`).
When `NO_COLOR` variable is defined (whatever the value you put in it), then ANSI will be deactivated and it's just going to be raw text.
Note: also modifying level of log for some errors to `WARN` (they are not unrecoverable errors from `bragi` point of view so `WARN` is enough).
=> feat: add possibility to deactivate ANSI formatting for logs

libs/places/src/poi.rs
Fix error: **request: Internal error InternalError { reason: SerializationError, info: "missing field `children`" }**
=> Fix serialize children

.github/workflows/master.yml, .github/workflows/master7.yml, .github/workflows/release.yml, .github/workflows/release7.yml
Debian Jessie 8 is now too old and the repositories have been archived. It starts to be really difficult to build anything with it. For the time being, we still need Debian packages built on Debian 8 (for `tyr-worker` on `navitia`). It seems that `navitia/debian8_dev` has everything we need.
Here is [a build that works](https://github.com/hove-io/mimirsbrunn/actions/runs/4552908750) (I simulated a build on `master` with [this commit](https://github.com/hove-io/mimirsbrunn/commit/9d328c553f9155bb7f7a3c8e4d7240b289dbc807)).
=> ci: use prebuild navitia images

.github/workflows/master.yml, .github/workflows/master7.yml, .github/workflows/release.yml, .github/workflows/release7.yml
The `matrix.version` was also used inside `build_dev.sh` (although only to name a temporary directory to make the build :shrug:). I hope this is the latest CI fix :upside_down_face:
=> ci: fix the call to build_dev.sh

.github/workflows/master.yml, .github/workflows/master7.yml, .github/workflows/release.yml, .github/workflows/release7.yml
Before, Debian packages were named `mimirsbrunn-jessie-v2.12.0.deb`. But with recent changes in the CI, and particularly with 070ea0f and 25aebd1, the new names of the Debian packages was changed to `mimirsbrunn-8-v2.12.0.deb`.
This PR brings back the old naming scheme.
=> ci: make the name of the Debian packages back to the old name

.github/workflows/master7.yml, .github/workflows/release7.yml, scripts/build_deb.sh
The CI workflow was broken when some parts have been removed from the `Cargo.toml` in 31d1defced203c34099a12a43d14f592f7c918fc.
=> ci: fix renaming of binaries with a suffix

libs/places/src/poi.rs, libs/places/src/stop.rs, libs/places/src/utils.rs
When feeding ElasticSearch with an old version of `mimir` (before #828), the `autocomplete_visible` field will not be present in ElasticSearch. However, if we deploy a recent `bragi` version, it will try to deserialize `Poi` and/or `Stop` but will fail with 
```json
{
"short": "query error",
"long": "missing field `autocomplete_visible`"
}
```
Having a default value on deserialization should fix that and make it backward compatible.
=> fix: make 'bragi' backward compatible with 'mimir'
