- Cargo.lock
- Cargo.toml
- build.rs
- src/bin/bano2mimir.rs
- src/bin/osm2mimir.rs
- src/objects.rs
- src/objects.rs.in
- src/rubber.rs
* move the serde stuff to objects.rs
* use the same connection string in bano2mimir and osm2mimir
* bano2mimir now takes either a directory or just a file in parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canaltp/mimirsbrunn/8)
> input parameters

- src/rubber.rs
the elasticsearch client does not handle http:// in the cnx string, so
remove it from the regexp.
also store the cnx string since curl is still used for the mapping
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canaltp/mimirsbrunn/10)
> corrections after review: do not put http:// in es client

- build_packages.sh
else the binary could not be completly cleaned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canaltp/mimirsbrunn/14)
> remove temporary install dir

- Cargo.lock
- src/bin/bano2mimir.rs
- src/bin/osm2mimir.rs
- src/lib.rs
- src/objects.rs.in
Admin without admin_centre are imported with coord at 0;0.
> import of admin_centre for admin with get_objets_and_deps

- Cargo.lock
- libs/mimir/src/objects.rs.in
- src/bin/bano2mimir.rs
- src/bin/osm2mimir.rs
http://jira.canaltp.fr/browse/NAVP-557
> index street without admin

- Cargo.lock
- Cargo.toml
- libs/mimir/Cargo.toml
- libs/mimir/src/objects.rs.in
- libs/skojig/Cargo.lock
- libs/skojig/Cargo.toml
- libs/skojig/src/api.rs
- libs/skojig/src/lib.rs
- libs/skojig/src/model.rs.in
- libs/skojig/src/query.rs
- src/boundaries.rs
* What has been done:
Replace the json query by rs_es
* What to do:
Place query code into Rubber?
Note:
* Filtered Query is deprecated according to the doc.
* The Missing clause should be replaced by must_not_have and exists clause
> use rs-es for search query

- libs/skojig/src/query.rs
wait a bit to merge it I do not have data to test it :smile:
> handle multi types in ES responses

- libs/skojig/src/api.rs
- libs/skojig/src/lib.rs
- libs/skojig/src/query.rs
not proud of the moves....
I put the API in a struct because I though it would be more convenient in the futur.
same, wait a bit to merge, cannot test it well here
> link the api to some params

- libs/mimir/src/objects.rs.in
- src/bin/bano2mimir.rs
- remove serialization of boundary since it's not used in ES
- invert coord in address id, so it's conform to kraken
- remove postal code from address name, to look like address from kraken
> just a few fixes

- .travis.yml
- Cargo.lock
- Cargo.toml
- libs/mimir/Cargo.toml
- libs/mimir/src/lib.rs
- libs/mimir/src/rubber.rs
- tests/bano2mimir_test.rs
- tests/rubber_test.rs
- tests/tests.rs
remove curl dependency
add some tests
> rubber refactoring

- Dockerfile
- libs/bragi/src/api.rs
- libs/bragi/src/model.rs.in
also better dockerfile, we gain 10mo...
> add version and es url to /status

- libs/bragi/src/model.rs.in
Error should be nested otherwise, and need to be fixed
**Jormun has to be modified for this new responses**
> We had a too much level in the json

- Cargo.lock
- Cargo.toml
- libs/bragi/Cargo.toml
- libs/bragi/src/lib.rs
- libs/bragi/src/model.rs.in
- libs/mimir/Cargo.lock
- libs/mimir/Cargo.toml
- libs/mimir/src/lib.rs
- libs/mimir/src/objects.rs.in
- libs/osm_builder/Cargo.toml
- src/admin_geofinder.rs
- src/bin/bano2mimir.rs
- src/bin/osm2mimir.rs
- src/boundaries.rs
- src/lib.rs
- tests/bragi_test.rs
- tests/rubber_test.rs
for the moment there are not quadtree plugged to this, we look for the
admins by looping through all admins.
The quadtree search will be done in another PR
TODO in this PR:
> link street to admin

- libs/bragi/src/model.rs.in
else jormungandr cannot parse the request
> we don't want null field, we hide them

- Cargo.lock
- Cargo.toml
- src/admin_geofinder.rs
- src/bin/osm2mimir.rs
- src/lib.rs
on fr-idf: 10min -> 3 min
on france: 55min (swapping a bit)
> use rtree from gst to find admin

- Cargo.lock
- Cargo.toml
- libs/mimir/src/objects.rs.in
- src/bin/osm2mimir.rs
- tests/osm2mimir_test.rs
Need https://github.com/CanalTP/mimirsbrunn/pull/65 to be merged to add
some tests.
Ticket concerned : http://jira.canaltp.fr/browse/NAVP-590
> mimir: merge of ways having same name and admins with level = city_level

- tests/bragi_test.rs
- tests/osm2mimir_bano2mimir_test.rs
some refacto
new tests
- search street in a shape that contains that street
- search street in a shape that not contain that street
- search admin in a shape that contains that admin
- search admin in a shape that not contain that admin
- Import osm + bano => 3 elasticsearch indices created
> added tests admin & way with shape

- README.md
- json/settings.json
- libs/bragi/src/model.in.rs
- libs/bragi/src/query.rs
- libs/docker_wrapper/src/lib.rs
- libs/mimir/src/objects.in.rs
- src/bin/osm2mimir.rs
- tests/bragi_test.rs
- tests/osm2mimir_bano2mimir_test.rs
- tests/osm2mimir_test.rs
> import pois type node

- src/admin_geofinder.rs
- src/bin/osm2mimir.rs
fix https://github.com/CanalTP/mimirsbrunn/issues/96
thanks to @TeXitoi
> AdminGeoFinder implements FromIterator

- Cargo.lock
- libs/bragi/Cargo.toml
- libs/bragi/src/query.rs
- libs/mimir/Cargo.toml
- libs/mimir/src/lib.rs
- libs/mimir/src/objects.in.rs
- src/admin_geofinder.rs
- src/osm_reader/admin.rs
- tests/bragi_test.rs
- tests/osm2mimir_test.rs
- tests/tests.rs
needs https://github.com/georust/rust-geojson/pull/56 to be merged
TODO:
> Serialize deserialize admin boundaries

- libs/bragi/src/model.in.rs
- libs/bragi/src/query.rs
- libs/mimir/src/objects.in.rs
- src/bin/stops2mimir.rs
- tests/bragi_test.rs
- tests/fixtures/stops.txt
> Stops in bragi

- src/bin/stops2mimir.rs
- tests/fixtures/stops.txt
less logs and better handling of the stop_area and visible flags
> better error handling

- libs/mimir/src/lib.rs
you can now trace the timestamp in log with the env var `LOG_TIME`
> add the possibility to trace the time in log

- libs/bragi/src/query.rs
- libs/docker_wrapper/src/lib.rs
- libs/mimir/src/rubber.rs
- src/admin_geofinder.rs
- src/boundaries.rs
- src/osm_reader/admin.rs
- src/osm_reader/poi.rs
- src/osm_reader/street.rs
- src/osm_reader/utils.rs
- tests/bragi_test.rs
- tests/tests.rs
filter to handle house numbers
we either want:
* to exactly match the document house_number
* or that the document has no house_number
we were also matching the zip code in this, so it was not working
geocoding tester fails:
before 938
after 817
> house number handling

- libs/bragi/src/api.rs
it will make http://par-vm191.srv.canaltp.fr:9000/ work
I allow everything, not sure if it's the right way to do this though
> add cors headers

- libs/bragi/src/query.rs
we boost more the admins and the stops as we want them in the first
results
This does not change the geocoding results as there are no stops (a few admins tests)
we also boost the zip code matching
this has a huge impact on geocoding tester
before:
882 fails
after:
695 fails
> change the query

- libs/bragi/src/model.in.rs
- src/bin/stops2mimir.rs
- src/osm_reader/mod.rs
- src/osm_reader/osm_utils.rs
- src/osm_reader/poi.rs
- src/osm_reader/street.rs
- src/utils.rs
- tests/bragi_bano_test.rs
- tests/bragi_stops_test.rs
change stops label, add it's city in the label
`chatelet (Paris)`
like it is done for the other objects
also fill the postcode
> add admin to stop label

- Cargo.lock
- libs/bragi/Cargo.toml
- libs/bragi/src/api.rs
- libs/bragi/src/query.rs
- tests/bragi_filter_types_test.rs
- tests/tests.rs
This PR uses https://github.com/datanel/queryst?branch=decode-params merged (https://github.com/rustless/queryst/pull/8) but no new release was  created
> Added filter by type

- tests/bragi_filter_types_test.rs
> forgot a test call

- json/settings.json
- libs/mimir/src/rubber.rs
- tests/bragi_synonyms_test.rs
- tests/tests.rs
- saint <=> st
- mairie <=> hotel de ville
...
> Added synonyms 

- libs/bragi/src/query.rs
Catch the error with following messages:
- "Elasticsearch Connection Error"
- "Index not found"
> bragi: error handling

- Cargo.lock
- Cargo.toml
- libs/bragi/Cargo.toml
- libs/bragi/src/api.rs
- libs/bragi/src/params.rs
- libs/bragi/src/query.rs
- libs/mimir/Cargo.toml
- libs/mimir/src/objects.rs
- tests/bragi_bano_test.rs
See https://github.com/benashford/rs-es/pull/107 for the modifications in rs-es
> Add a reverse geocoding API to bragi

- libs/mimir/src/lib.rs
for easier parse with kibana
needed by https://github.com/CanalTP/fab_mimir/pull/19
> change log format

- libs/bragi/src/query.rs
> Tune geolocation weight function

- Cargo.lock
- Cargo.toml
- libs/bragi/Cargo.toml
- libs/bragi/src/lib.rs
- src/bin/bano2mimir.rs
- src/bin/osm2mimir.rs
- src/bin/stops2mimir.rs
To review and merge after #160 is merged.
> Migrate to structopt

- src/bin/stops2mimir.rs
- tests/fixtures/stops.txt
Concerned Ticket: https://jira.canaltp.fr/browse/NAVITIAII-2266
> stops2mimir: Reject stop with invalid coordinate.

- libs/bragi/src/api.rs
- libs/bragi/src/model.rs
- libs/bragi/src/query.rs
- libs/mimir/src/objects.rs
- libs/mimir/src/rubber.rs
- src/bin/osm2mimir.rs
- src/osm_reader/poi.rs
- tests/bragi_poi_test.rs
Add attribut address in poi. It can be of the type Addr or Street.
Ticket concerned: https://jira.canaltp.fr/browse/NAVP-721
> Add address in poi for autocomplete

- libs/bragi/src/model.rs
- libs/mimir/src/objects.rs
- src/bin/ntfs2mimir.rs
- src/bin/stops2mimir.rs
- tests/bragi_ntfs_test.rs
- tests/fixtures/ntfs/object_codes.txt
- tests/fixtures/ntfs/object_properties.txt
- tests/fixtures/ntfs/stops.txt
https://jira.canaltp.fr/browse/NAVP-726
> add timezone, codes and properties in stop_area

- Cargo.lock
- libs/bragi/Cargo.toml
- libs/bragi/src/lib.rs
> Access log

- libs/bragi/src/model.rs
- libs/mimir/src/objects.rs
- src/bin/ntfs2mimir.rs
- src/bin/stops2mimir.rs
- src/stops.rs
- tests/bragi_ntfs_test.rs
- tests/fixtures/ntfs/contributors.txt
- tests/fixtures/ntfs2/contributors.txt
- tests/fixtures/ntfs2/datasets.txt
- tests/tests.rs
import feed_publishers for stop_area
https://jira.canaltp.fr/browse/NAVP-717
> import feed_publishers

- .travis.yml
- Cargo.toml
- libs/bragi/src/api.rs
- libs/bragi/src/lib.rs
- libs/bragi/src/query.rs
- libs/mimir/src/objects.rs
- libs/mimir/src/rubber.rs
- src/admin_geofinder.rs
- src/bin/bano2mimir.rs
- src/bin/cosmogony2mimir.rs
- src/bin/mimir_init.rs
- src/bin/ntfs2mimir.rs
- src/bin/openaddresses2mimir.rs
- src/bin/osm2mimir.rs
- src/bin/stops2mimir.rs
- src/osm_reader/admin.rs
- src/osm_reader/street.rs
- src/stops.rs
- tests/bragi_poi_test.rs
- tests/bragi_stops_test.rs
- tests/tests.rs
> update to latest stable

- README.md
add a section about the datasources and list all components
this is a first step for #231
> slightly improve doc

- Cargo.lock
- libs/bragi/src/api.rs
- libs/bragi/src/params.rs
- libs/bragi/src/query.rs
- libs/mimir/src/rubber.rs
The `timeout` is in milliseconds.
I'm considering if we need to have a default timeout or not, probably...
Only the first commit (2f7461d) is worth reading, others are fmt and cargo stuff.
> Add a timeout parameters in the API and use it when calling ES

- Cargo.lock
- libs/bragi/Cargo.toml
- libs/bragi/src/lib.rs
By default 8 threads are created by cpu core, like before.
> Add an option to choose the number of threads in bragi

- src/utils.rs
we wrap the real `launch_run` in another method to std::exit after the
destruction of the logger (so we won't loose any messages)
https://docs.rs/slog-async/2.3.0/slog_async/#beware-of-stdprocessexit
else we get truncated messages at the end (especially visible when there
is an early error, we had no log at all or truncated json)
> fix logger destruction

- libs/bragi/src/api.rs
- libs/bragi/src/query.rs
- libs/docker_wrapper/src/lib.rs
- libs/mimir/src/rubber.rs
- src/addr_reader.rs
- src/admin_geofinder.rs
- src/bin/bano2mimir.rs
- src/bin/cosmogony2mimir.rs
- src/bin/mimir_init.rs
- src/bin/ntfs2mimir.rs
- src/bin/openaddresses2mimir.rs
- src/bin/osm2mimir.rs
- src/bin/stops2mimir.rs
- src/osm_reader/admin.rs
- src/osm_reader/poi.rs
- src/osm_reader/street.rs
- tests/bragi_stops_test.rs
- tests/cosmogony2mimir_test.rs
- tests/osm2mimir_test.rs
- tests/rubber_test.rs
- tests/tests.rs
this is why travis is not happy with #256.
I don't think it blocks the merge of #256 though
> update rust fmt after rust 1.29 update

- README.md
- docs/readme.md
Before the release of Qwant Maps in a few days, we try to update all the documentation of the systems we are using.
This is why this PR proposes simple changes of the readme to make it more clear, if possible.
You can see below a screenshot of the changes "before/after".
> Improve Readme

- docker/Dockerfile_bragi
- docker/Dockerfile_import
Should fix https://ci.navitia.io/view/mimir/job/mimirsbrunn_master_package/
> Update docker containers to stretch

- README.md
> Improve building instructions

- Cargo.lock
- Cargo.toml
- src/bin/bano2mimir.rs
- src/bin/bragi.rs
- src/bin/cosmogony2mimir.rs
- src/bin/mimir_init.rs
- src/bin/ntfs2mimir.rs
- src/bin/openaddresses2mimir.rs
- src/bin/osm2mimir.rs
- src/bin/stops2mimir.rs
- src/lib.rs
- src/osm_reader/poi.rs
- src/osm_reader/street.rs
- src/stops.rs
- tests/bano2mimir_test.rs
- tests/bragi_bano_test.rs
- tests/bragi_ntfs_test.rs
- tests/bragi_poi_test.rs
- tests/canonical_import_process_test.rs
- tests/openaddresses2mimir_test.rs
- tests/rubber_test.rs
- tests/tests.rs
The subcrates are not handled by this PR.
> extern crate cleanup in src and tests

- build_image/Dockerfile
this will also hopefully fix the internal CI
> jimmycuadra/rust is deprecated, use official, up to date image

- src/bin/cosmogony2mimir.rs
navitia needs some id to be formated in an uggly way :wink:
> add some retrocompatibility on some admin's id

- src/bin/cosmogony2mimir.rs
the format_id was broken we could have a zone id equals to it's parent
id, resulting in infinite loop for some look up
> fix format_id in cosmogony

- README.md
- documentation/architecture.md
- documentation/components.md
- documentation/images/archi.svg
- documentation/readme.md
- documentation/test_strategy.md
follow https://github.com/CanalTP/mimirsbrunn/issues/231
Revamp a bit the documentation.
Feel free to tell me if some parts are difficult to understand or not
correctly organized.
poke @amatissart 
There is still a lot of TODOs, and I don't plan of addressing them all in this PR, but this should be a better starting point for someone discovering this repository.
> First shot at a revamped documentation

- Cargo.lock
- Cargo.toml
- src/bin/openaddresses2mimir.rs
openaddresses directory can contain some subdirectory and metadatafiles.
this add the capability to read all nested csv files in the directory.
> improve a bit the reading of openaddresses files

- libs/bragi/src/prometheus_middleware.rs
lets take the start time before calling the handler :D
> fix prometheus timing

- libs/bragi/benches/basic.rs
- libs/bragi/src/model.rs
- libs/mimir/src/objects.rs
- src/bin/cosmogony2mimir.rs
- src/labels.rs
- src/osm_reader/admin.rs
- tests/canonical_import_process_test.rs
- tests/cosmogony2mimir_test.rs
> Add administrative regions for admins

- README.md
From Readme Remove broken link to components
> Remove broken link to components

- documentation/components.md
I am a newbie in Rust. But I need to do this change to be able to run with cargo.
> Fix cargo run call from Components doc

- documentation/components.md
> Doc: Fist load admin

- Cargo.lock
- Cargo.toml
- libs/bragi/Cargo.toml
- libs/bragi/src/query.rs
- libs/mimir/Cargo.toml
- libs/mimir/src/rubber.rs
- scripts/import2mimir.sh
- src/bin/ntfs2mimir.rs
- src/bin/poi2mimir.rs
- src/bin/stops2mimir.rs
- src/stops.rs
This PR contains two changes:
- the stop weight is now a function of the admin weight
- the function score uses a weight
> Stop weight use admin

- src/bin/cosmogony2mimir.rs
Europe import now take 2go of RAM in place of 20go.
The import took 11 minutes for 411408 admins, it was taking 17 minutes before but I was swapping
> reduce memory usage of cosmogony2mimir

- src/addr_reader.rs
This PR only introduces debug information: it counts the number of imported addresses for each country and display the result.
> Log addresses count per country

- Cargo.lock
- Cargo.toml
- libs/bragi/Cargo.toml
- libs/docker_wrapper/Cargo.toml
- libs/mimir/Cargo.toml
- libs/tools/Cargo.toml
increment versions across all projects within mimirsbrunn
> Increment version => 1.15

- build.rs
Hi! This is just a tiny PR to add a comment that was requested in previous PR: https://github.com/CanalTP/mimirsbrunn/pull/411#discussion_r456492148
> Document build script specific behavior

- Cargo.toml
- libs/bragi/Cargo.toml
- libs/docker_wrapper/Cargo.toml
- libs/mimir/Cargo.toml
- libs/tools/Cargo.toml
I wish to increment to version 1.16.0 because we introduced a lot of changes since the last release
> Bump Version 1.16.0

- .github/workflows/build_package.yml
so that packages are easier to download than from the CI
> Build deb package in gihub actions

- libs/bragi/src/lib.rs
- libs/bragi/src/routes/autocomplete.rs
- tests/cosmogony2mimir_test.rs
- tests/osm2mimir_test.rs
- tests/poi2mimir_test.rs
- tests/stops2mimir_test.rs
- tests/tests.rs
These are mostly changes due to clippy.
> [Changed] Update to rust 1.48

- Cargo.toml
- Makefile
- libs/bragi/Cargo.toml
- libs/docker_wrapper/Cargo.toml
- libs/mimir/Cargo.toml
- libs/tools/Cargo.toml
This adds a few lines to each Cargo.toml that clippy suggested
> [Fixed] Missing make check command, linting

- src/bin/osm2mimir.rs
This was confusing in the log, so I made it a bit more explicit
> [Fixed] Confusing logs

- src/bin/poi2mimir.rs
- tests/bragi_poi_test.rs
**Why this PR** : To standardize the POI identifiers accross tools at Kisio
> Fix id poi format

- .github/workflows/master.yml
- .github/workflows/release.yml
- .github/workflows/workflow.yml
New jobs added:
workflow.yml: run on all pull request, push,  master/release branches
master.yml: run on push on master branch
release.yml: run on push on release branch
> New jobs added

- .github/workflows/create_publish_bragi_docker.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- Makefile
- old_Makefile
- Rename Makefile by old_Makefile
- Create new Makefile for create and publish bragi images
- Add new job for publish bragi images on public registry
- Publish messages on slack
> Create, publish and remove bragi images

- .github/workflows/release.yml
> [CI] publish release in principal page github 

- libs/mimir2/src/adapters/secondary/elasticsearch/configuration.rs
- libs/mimir2/src/adapters/secondary/elasticsearch/internal.rs
- libs/mimir2/src/adapters/secondary/elasticsearch/mod.rs
- libs/mimir2/src/adapters/secondary/elasticsearch/storage.rs
- src/addr_reader.rs
- src/admin.rs
- src/bin/cosmogony2mimir.rs
- tests/steps/admin.rs
restricts access to 'super' for elasticsearch internal
> Pub crate internal

- libs/places/src/utils.rs
This is just a small mistake that I've done in my previous PR.
> default dataset name should be `default`

- libs/mimir2/src/utils/docker.rs
- src/bin/bano2mimir.rs
This little patch is to restrict the scope of the test to bano2mimir.
> Just check bano2mimir

- scripts/import2mimir.sh
Updates the script to the new command line, fixes a few things in the script, improves the display
> Adapt import script

- Cargo.lock
- config/elasticsearch/templates/indices/mimir-addr.json
- config/elasticsearch/templates/indices/mimir-admin.json
- config/elasticsearch/templates/indices/mimir-poi.json
- config/elasticsearch/templates/indices/mimir-stop.json
- config/elasticsearch/templates/indices/mimir-street.json
- src/bin/ntfs2mimir.rs
- src/stops.rs
Simple PR to make sure the type is correctly indexed
> Add constant keywords to indices templates

- config/elasticsearch/templates/components/mimir-base.json
- libs/places/src/poi.rs
This will allow sorting over weights.
> enable mapping for weight

- config/bragi/default.toml
- libs/mimir/src/adapters/primary/bragi/api.rs
- libs/mimir/src/adapters/primary/bragi/handlers.rs
- libs/mimir/src/adapters/primary/bragi/routes.rs
- src/bragi/server.rs
- src/bragi/settings.rs
Default in Bragi only : 
2s for /autocomplete
200ms for /reverse & /features
> [Bragi] Specific Timeout per /endpoint

- benches/searching.rs
- libs/mimir/src/adapters/primary/bragi/handlers.rs
- libs/mimir/src/adapters/primary/common/dsl.rs
- src/bin/query.rs
- tests/steps/search.rs
> Fuzzy query

- benches/searching.rs
- libs/mimir/src/adapters/primary/bragi/handlers.rs
- libs/mimir/src/adapters/primary/common/dsl.rs
- src/bin/query.rs
- tests/steps/search.rs
To reproduce the previous behavior : -> Request elasticsearch in `PREFIX` mode first (fast and confident)
-> If no results found: request in `FUZZY` mode (with ngrams)
> Add fuzzy query

- libs/mimir/src/adapters/primary/common/dsl.rs
Reproduce the consideration of coordinates as in [Bragi2](https://github.com/CanalTP/mimirsbrunn/blob/da72c2fac5887d3c6fbbc2b4d69201ecb9a95319/libs/bragi/src/query.rs#L117)
> Fix autocomplete with coord

- Cargo.lock
- libs/mimir/Cargo.toml
- libs/mimir/src/adapters/primary/bragi/handlers.rs
Add distance in bragi response.
distance between query coord and place object: As in [Bragi2](https://github.com/CanalTP/mimirsbrunn/blob/da72c2fac5887d3c6fbbc2b4d69201ecb9a95319/libs/mimir/src/rubber.rs#L180)
> Add distance in bragi response

- benches/searching.rs
- libs/mimir/src/adapters/primary/bragi/handlers.rs
- libs/mimir/src/adapters/primary/common/dsl.rs
- src/bin/query.rs
- src/settings/ntfs2mimir.rs
- src/stops.rs
- tests/steps/search.rs
> Fix autocomplete-explain API

- src/bin/bano2mimir.rs
- src/bin/cosmogony2mimir.rs
- src/bin/ctlmimir.rs
- src/bin/ntfs2mimir.rs
- src/bin/openaddresses2mimir.rs
- src/bin/osm2mimir.rs
- src/bin/poi2mimir.rs
🤖 This is an automatic PR 🤖
Clippy suggests the following changes
> [Clippy] Code maintenance

- README.md
To solve the problem : https://github.com/CanalTP/mimirsbrunn/issues/723 
Error : 
ERROR Connection Error: Elasticsearch Connection Error: error sending request for url (http://localhost:9202/): error trying to connect: tcp connect error: Connection refused (os error 111)
> Update Readme : Fix step 4 of the section "Running"

- libs/mimir/src/adapters/primary/bragi/handlers.rs
> fix: missing metric bragi_elasticsearch_request_duration_seconds

- libs/mimir/src/adapters/primary/bragi/handlers.rs
/features return a 404 when elasticsearch returns an empty response
https://navitia.atlassian.net/browse/NAV-1337
> Fix http response code for empty /features

- docker/bragi/Dockerfile
- docker/mimirsbrunn/Dockerfile
the comment was interpreted as arguments to apt-get before 
see https://github.com/hove-io/mimirsbrunn/actions/runs/2535537470
> fix comment in dockerfile

- .github/workflows/docker.yml
Correlated with https://github.com/hove-io/bragi-aws-assets/pull/77 which should be merged before.
> ci: trigger external job when new Docker image is produced

- libs/places/src/poi.rs
> fix: normalize_id already add ':'

- .github/workflows/master.yml
I forgot a few more :facepalm:
> ci: fix (again) --force-yes

- Cargo.lock
- Cargo.toml
- src/bragi/main.rs
- src/bragi/tests.rs
- src/utils/logger.rs
Please review and merge #815 first.
> test: add simple test on '/status'

- config/elasticsearch/templates/components/mimir-base.json
- config/elasticsearch/templates/components/mimir-dynamic-mappings.json
- src/bragi/tests.rs
> fix: take care of prefix and elision correctly

- src/admin.rs
- src/bin/cosmogony2mimir.rs
- src/bragi/tests.rs
> feat: rebuild labels in 'cosmogony2mimir'
